#+TITLE:  =~/me/=
#+AUTHOR: Ben Sima
#+EMAIL:  bensima@gmail.com

This is meant to be a portable environment system. My own shell
commands, my favorite libraries, my favorite settings for my favorite
languages, my own static www site(s), etc etc.

Whenever possible, I try to keep notes and code as [[http://orgmode.org/][org-mode
files]]. That way, I can actually remember why and how I did
something. Most of these org files will be [[http://orgmode.org/manual/Extracting-source-code.html][tangled]] somewhere else on
my system. For example, you can read through =system/emacs.org= to see
how I setup my emacs config. Everything in there should be 100%
reproducible and self-contained.

* Directory structure

How should this be structured? Ideally, I want all my system stuff to
be separte from my code, from my website, etc, but I want them all to
be able to call each other too.

#+BEGIN_EXAMPLE
~
|-/me/
  |- system/   (for all of my environment/system setup)
  |- www/      (my static website at www.bsima.me)
  |- org/      (my private org files - sync'd via bittorrent/dropbox/rsync)
  |- maths/    (my maths files - notes, simulations, algorithms - for continuing my education)
     |- euler/ (my project euler solutions)
#+END_EXAMPLE

* Todo

1. load [[https://github.com/fukamachi/shelly][Shelly]] and setup a continuous Common Lisp REPL that I can use
   as a sort-of-alternative to bash/zsh.
