#+TITLE:  =~/me/=
#+AUTHOR: Ben Sima
#+EMAIL:  bensima@gmail.com

This is meant to be a portable environment system. My own shell
commands, my favorite libraries, my favorite settings for my favorite
languages, my own static www site(s), etc etc.

Whenever possible, I try to keep notes and code as [[http://orgmode.org/][org-mode
files]]. That way, I can actually remember why and how I did
something. Most of these org files will be [[http://orgmode.org/manual/Extracting-source-code.html][tangled]] somewhere else on
my system. For example, you can read through [[file:system/emacs.org][emacs.org]] to see
how I setup my emacs config. Everything in there should be 100%
reproducible and self-contained.

* Directory structure

#+BEGIN_EXAMPLE
~
|-/me/
  |- system/   (for all of my environment/system setup)
  |- www/      (my static website at www.bsima.me)
  |- org/      (my private org files - sync'd via bittorrent/dropbox/rsync)
  |- notes/    (notes I take when I learn stuff)
  |- ...
#+END_EXAMPLE

* Blogging

See [[file:system/spacemacs.org::*=bsima.me=][=bsima.me=]].

* TODO Common Lisp Scripting

Lisp is way better than shell. I can use the following as a portable

- [[https://gitlab.common-lisp.net/asdf/asdf/blob/master/uiop/README.md][uiop]] for executing system commands in a portable way
- [[https://github.com/snmsts/roswell/][roswell]] for scripting ([[https://github.com/snmsts/roswell/blob/master/scripts/release.ros][example]])
- [[https://github.com/fukamachi/shelly][Shelly]] for quick access to Common Lisp from the command line
  1. load [[https://github.com/fukamachi/shelly][Shelly]] and setup a continuous Common Lisp REPL that I can use
     as a sort-of-alternative to bash/zsh.
  2. Shelly should load all the lisp scripts in =./bin/=, so I have
     access to them from both the shell and the repl
  3. [[file:system/lisp.org][.sbclrc]] should also load lisp scripts in =./bin/= and load a new
     directory called =./lib/=, where I can put more library-like code.
-
