---
title: Resume
id: resume
---

I write **computer code** and have experience in **web apps**, **data science** and **visualization**, **statistics** and **computational biology**, and **ecommerce applications**.

I have professional experience in...

* JavaScript
* Clojure
* Python
* Ruby
* Perl
* PHP
* R

...and I have worked with, C/C++, Common Lisp, Mathematica, Matlab/Octave, Haskell and OCaml in side-projects.

I graduated from the **Rochester Institute of Technology** where I studied philosophy and biotechnology.

[View my printable, traditional resume here](/pages/print-resume.html)

## Overview of my experience

Roughly in chronological order (most-recent first), here is a list of some of my projects for the past 3-ish years in order to highlight my contributions and skills...

### Salzman Group

I'm currently employed as a Ruby on Rails developer for the Salzman Group. Our primary Rails application is [WholeLatteLove.com](https://wholelattelove.com).

### Nebula Biotech

An ongoing project to develop open-source biotechnology devices for multiple target platforms such as the Arduino, etc. Our current project involves designing and programming a safe, non-invasive potentiostat suitable for everyday blood analysis. All development is being done in the open ([Trello][t], [GitHub][gh]). Our platform is a combination of C and Matlab right now, and we plan on finishing the [Protochip](https://github.com/nebulabio/protochip) as an Arduino shield for customizable blood tests.

[t]: https://trello.com/b/Tb4b74V5/protochip
[gh]: https://github.com/nebulabio

### Aristotl

[Aristotl](https://github.com/bsima/aristotl) is a personal project. It is an attempt to develop an API for philosophical data, references, papers, associations between separate concepts and philosophers, etc. WIP.

### Thinkful.com

* Peer mentor new students in Python
* Responsibilities include code review, instructional lessons, pair programming, and general tutoring
* Time commitment from 4-8 hours per week with my students, depending on how many students I have at a time

### Nebula Sports

A past startup project that lasted for about a year. My main role was in guiding the scientific research, while solely doing the fundraising (grants and private investment).

1. We developed a novel headgear padding for athletics. In a 4-person team, we developed an algorithm for optimizing our padding to a specific position within a specific sport. Patent concerns made us shut down this project.
1. Next, we prototyped and programmed an accelerometer that would live inside of a helmet and tell the athlete the severity of the impact. Reebok released the [CheckLight](http://www.mc10inc.com/consumer-products/sports/checklight/) product before we finished developing.

All algorithm programming was done in Matlab, while presentations and marketing material were created as web pages with standard HTML and JavaScript.

### Computational Genomics Research

With [Dr. Babbitt](http://www.rit.edu/cos/gregory-babbitt) at RIT, we developed a [Perl program](https://github.com/bsima/yeast-TRX) to study the flexibility (TRX score) of DNA and RNA molecules. This involved parsing a couple gigabytes of genomic data, normalizing and plotting the data, and doing a weighted Pearson correlation between the DNA and the RNA GC-rich regions.
