#+TITLE:  Profiles
#+AUTHOR: Ben Sima
#+EMAIL:  bensima@gmail.com
#+PROPERTY: tangle ~/.profile
#+PROPERTY: comments org
#+PROPERTY: shebang #!/bin/sh
#+DESCRIPTION: Global environment varialbes for all shells

This generates my =~/.profile=, which can establish settings across all shell
environments. This means it will be portable across all environments and shells
that I might use. Think of it as "portable shell scripting", like "portable
Common Lisp" or "portable C." Maybe.

The differences between =~/.profile=, =~/.bash_profile=, and =~/.bashrc= are
actually kinda interesting, from a nerdy-computing-history perspective. Read
about them [[http://superuser.com/a/183980][here]]. What I took away from that explanation is that most of my stuff
will go into =~/.profile=, but for changing my prompt and setting up aliases, I
should use =~/.bashrc= (and a [[file:shell.org][shell.org]] to go with it).

* Check for bash

If I'm running bash, then include =.bashrc= if it exists.

#+BEGIN_SRC sh
if [ -n "$BASH_VERSION" ]
then
  if [ -f "$HOME/.bashrc" ]
  then
    . "$HOME/.bashrc"
  fi
fi
#+END_SRC

* Path

Only add the following directories if they exist. For portability!

#+BEGIN_SRC sh
OLDPATH=$PATH
PATH=$HOME/bin

for DIR in /usr/local/git/bin /opt/local/bin /opt/local/sbin /usr/local/bin /usr/local/sbin $HOME/bin $HOME/me/bin
do
  if [ -d $DIR ]
  then
    PATH=$PATH:$DIR
  fi
done

PATH=$PATH:$OLDPATH
#+END_SRC

* Editor

Set =EDITOR= to use emacs in the terminal:

#+BEGIN_SRC sh
export EDITOR="emacsclient -t"
#+END_SRC
  
* Ruby

Load [[https://github.com/sstephenson/rbenv][rbenv]] if it is installed. I also need the [[https://github.com/sstephenson/ruby-build][ruby-build]] plugin for rbenv,
which provides the =rbenv install= command.

To load rbenv into the shell, I need to add =~/.rbenv/bin= to the =$PATH= and
eval this =init= command.
  
#+BEGIN_SRC sh
function load_rbenv {
  export PATH="./bin:$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
}

if [ -d "$HOME/.rbenv" ]
then
  load_rbenv
else
  git clone https://github.com/sstephenson/rbenv.git "$HOME/.rbenv"
  git clone https://github.com/sstephenson/ruby-build.git "$HOME/.rbenv/plugins/ruby-build"
  load_rbenv
fi
#+END_SRC

* Python

Load [[https://github.com/yyuu/pyenv][pyenv]] if it's installed. The pyenv installer simply creates a =~/.pyenv=
directory, so we check for that. If it's not installed, then install it.
  
  #+BEGIN_SRC sh
function load_pyenv {
  export PATH="$HOME/.pyenv/bin:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
}

if [ -d "$HOME/.pyenv" ]
then
  load_pyenv
else
  curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
  load_pyenv
fi
  #+END_SRC

  Now I can do =pyenv update= to be sure I have the latest version.

* Nix

This line is automatically added to the bottom of your =.profile= when you
install [[https://nixos.org/nix/][Nix]]:

#+BEGIN_SRC sh
if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then . "$HOME/.nix-profile/etc/profile.d/nix.sh"; fi
#+END_SRC

* Google Cloud

This updates =PATH= for the Google Coud SDK and enables shell command completion
for =gcloud=:

#+BEGIN_SRC sh
if [ -d "$HOME/google-cloud-sdk" ]; then
  source "$HOME/google-cloud-sdk/path.bash.inc"
  source "$HOME/google-cloud-sdk/completion.bash.inc"
fi
#+END_SRC
