#+title:      My Spacemacs Configuration
#+author:     Ben Sima <bensima@gmail.com>
#+desciption: A literate programming version of my configs for Spacemacs.
#+property:   tangle ~/.spacemacs
#+property:   comments org
#+property:   eval no-export

* =dotspacemacs=

This generates my =~/.spacemacs= file. I've begun using [[https://github.com/syl20bnr/spacemacs][Spacemacs]] instead of my
custom emacs config because of the great community and sensible builds, but I
still want some of my own customizations, so this file retains a lot of those.

** Default layers

The =dotspacemacs/layers= function declares what layers to bring in from the
core Spacemacs code. Layers are just preconfigured modules, usually wrapping one
or more emacs packages. All layers can be seen in the [[https://github.com/syl20bnr/spacemacs/tree/master/layers][=spacemacs/layers=]]
directory.

The settings here are:

- *dotspacemacs-distribution* - This is the base distribution to use, contained
  in the =+distribution= layer. Can either ber =spacemacs-base= or =spacemacs=.
- *dotspacemacs-configuration-layer-path* - A list of additional paths where I
  might keep my own layers. Paths must have a trailing slash. This is useful if
  I have personal layers that I don't want to submit back upstream, or haven't
  finished yet.
- *dotspacemacs-configuration-layers* - A list of layers that I want to load. I
  can load all the available layers by replacing the list with the symbol =all=.
- *dotspacemacs-additional-packages* - A list of additional packages I want
  without being wrapped in a layer. Configuration for these can be put in
  =dotspacemacs/config=.
- *dotspacemacs-excluded-packages* - A package blacklist
- *dotspacemacs-delete-orphan-packages* - If non-nil, Spacemacs will delete
  installed packages that aren't included in the layers or packages I included above.

#+BEGIN_SRC elisp
(defun dotspacemacs/layers ()
  (setq-default
    dotspacemacs-distribution 'spacemacs
    dotspacemacs-configuration-layer-path '()
    dotspacemacs-configuration-layers
    '( auto-completion
       better-defaults
       emacs-lisp
       shell
       git
       github
       dockerfile
       yaml
       markdown
       org
       bsima
       org-journal
       jabber
       xkcd
       emoji
       clojure
       java
       common-lisp
       ;;shen
       racket
       ;;python
       haskell
       ocaml
       rust
       c-c++
      )
    dotspacemacs-additional-packages '( helm-lobsters
                                        sx
                                        circe
                                        org-journal )
    dotspacemacs-excluded-packages '()
    dotspacemacs-delete-orphan-packages t))
#+END_SRC

** Initialization

The =dotspacemacs/init= function is called at the very startup of Spacemacs
initialization, /before layers are configured/. Don't put user code in here,
just modify the given variables.

#+BEGIN_SRC elisp
(defun dotspacemacs/init ()
  (setq-default
    dotspacemacs-editing-style   'hybrid
    dotspacemacs-verbose-loading nil
    dotspacemacs-startup-banner  nil
    dotspacemacs-startup-lists   '(recents projects bookmarks)
    dotspacemacs-themes '( leuven
                           spacemacs-light
                           spacemacs-dark
                           solarized-light
                           solarized-dark
                           monokai
                           zenburn )
    dotspacemacs-colorize-cursor-according-to-state t
    dotspacemacs-default-font '("Source Code Pro"
                                :size 13
                                :weight normal
                                :width normal
                                :powerline-scale 1.1)
    dotspacemacs-leader-key "SPC"
    dotspacemacs-emacs-leader-key "M-m"
    dotspacemacs-major-mode-leader-key ","
    dotspacemacs-major-mode-emacs-leader-key "C-M-m"
    dotspacemacs-command-key ":"
    dotspacemacs-remap-Y-to-y$ t
    dotspacemacs-auto-save-file-location 'cache
    dotspacemacs-use-ido nil
    dotspacemacs-helm-resize nil
    dotspacemacs-helm-no-header nil
    dotspacemacs-helm-position 'bottom
    dotspacemacs-enable-paste-micro-state nil
    dotspacemacs-which-key-delay 0.4
    dotspacemacs-which-key-position 'bottom
    dotspacemacs-loading-progress-bar t
    dotspacemacs-fullscreen-at-startup nil
    dotspacemacs-fullscreen-use-non-native nil
    dotspacemacs-maximized-at-startup nil
    dotspacemacs-active-transparency 90
    dotspacemacs-inactive-transparency 90
    dotspacemacs-mode-line-unicode-symbols t
    dotspacemacs-smooth-scrolling t
    dotspacemacs-smartparens-strict-mode nil
    dotspacemacs-highlight-delimiters 'all
    dotspacemacs-persistent-server nil
    dotspacemacs-search-tools '("ag" "pt" "ack" "grep")
    dotspacemacs-default-package-repository nil
    ))
#+END_SRC

** User Initialization

I can put any user code here :)

#+BEGIN_SRC elisp
(defun dotspacemacs/user-init ()
  )
#+END_SRC

** User Configuration

Called at the very end of Spacemacs intitialization and layer configuration,
this function is good for my own customizations. Some highlights:

- Use =SPC t t= to toggle syntax highlighting
- org-journal and org-agenda configs
- jabber account setup, =SPC a j= will connect to jabber

#+BEGIN_SRC elisp
(defun dotspacemacs/user-config ()
  (setq
    display-time-format "%k:%M"
    powerline-default-separator nil
    clojure-enable-fancify-symbols t

    jabber-account-list      '(("bensima@gmail.com"
                               (:network-server . "talk.google.com")
                               (:connection-type . ssl)))
    jabber-history-enabled    t
    jabber-use-global-history nil
    jabber-backlog-number     40
    jabber-backlog-days       30

    org-todo-keywords       '((sequence "TODO" "IN PROGRESS" "|" "DONE" "DELEGATED"))
    org-default-tasks-file  "~/Dropbox/org/tasks.org"
    org-capture-templates   '(("t" "Task entry"
                               entry (file+function org-default-tasks-file bs/first-header)
                               "* TODO %?\n\n %i\n\n From: %a"
                               :empty-lines 1))
    org-journal-dir         "~/Dropbox/org/journal/"
    org-journal-date-format "#+TITLE: Journal Entry :: %Y-%b-%d (%A)"
    org-agenda-files        '("~/Dropbox/org/tasks.org"
                              "~/workspace/liaison/dm-schema/schema.org"))
  (display-time-mode t)
  (evil-leader/set-key "tt" 'font-lock-mode)
      (evil-leader/set-key "aoI" 'org-clock-in))
#+END_SRC

* Additional Layers
** Journal

First bring in the [[https://github.com/bastibe/org-journal][org-journal]] package and setup Spacemacs keybindings. Journal
files are named with the date sans the =.org= extension, so we need to add these
files to org-mode.

#+BEGIN_SRC elisp :tangle ~/.emacs.d/private/org-journal/packages.el
(setq org-journal-packages '(org-journal))

(defun org-journal/init-org-journal ()
  (use-package org-journal
    :config
    (progn
      (add-to-list 'auto-mode-alist '(".*/[0-9]*$" . org-mode))
      (global-set-key (kbd "C-c f j") 'journal-file-today)
      (global-set-key (kbd "C-c f y") 'journal-file-yesterday)
      (evil-leader/set-key
        "aojn" 'org-journal-new-entry
        "aojs" 'org-journal-search
        "aojd" 'org-journal-new-date-entry
        "aojr" 'org-journal-read-entry
        "aojj" 'org-journal-next-entry
        "aojk" 'org-journal-previous-entry
        "aojt" 'journal-file-today
        "aojy" 'journal-file-yesterday))))
#+END_SRC

Helper functions for getting journal files.

#+BEGIN_SRC elisp :tangle ~/.emacs.d/private/org-journal/funcs.el
(defun get-journal-file-today ()
  "Return filename for today's journal entry"
  (let ((daily-name (format-time-string "%Y%m%d")))
    (expand-file-name (concat org-journal-dir daily-name))))

(defun journal-file-today ()
  "Create and load a journal file based on today's date."
  (interactive)
  (find-file (get-journal-file-today)))

(defun get-journal-file-yesterday ()
  "Return filename for yesterday's journal entry."
  (let ((daily-name (format-time-string "%Y%m%d" (time-subtract (current-time) (days-to-time 1)))))
    (expand-file-name (concat org-journal-dir daily-name))))

(defun journal-file-yesterday ()
  "Creates and load a file based on yesterday's date."
  (interactive)
  (find-file (get-journal-file-yesterday)))

(defun bs/first-header ()
  (goto-char (point-min))
  (search-forward-regexp "^\* ")
  (beginning-of-line 1)
  (point))
#+END_SRC

** Private layer

*** =bsima.me=

I use orgmode for notes, mostly in the [[file:../notes][notes]] directory. The code blocks below
allow me to compile all of my notes into HTML, and then I can upload them to a
server somewhere. Lately I've just been publishing them to Amazon S3, and
routing [[http://www.bsima.me][bsima.me]] to the public-facing S3 bucket.

I must define the stylesheets and fonts that go into the =<head>= of every
page.

#+BEGIN_SRC elisp :tangle ~/.emacs.d/private/bsima/config.el
(defvar bs-site-head
  "<link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic|PT+Serif:400,700,400italic,700italic'>
   <link rel='stylesheet' type='text/css' media='screen' href='http://openfontlibrary.org/face/fantasque-sans-mono'/>
   <link rel='stylesheet' type='text/css' href='/assets/css/main.css' />")
#+END_SRC

Get rid of the default CSS that orgmode inlines with every page, the validate
link, and the postamble footer stuff:

#+BEGIN_SRC elisp :tangle ~/.emacs.d/private/bsima/config.el
(setq org-html-head-include-default-style nil)
(setq org-html-validation-link nil)
(setq org-html-postamble nil)
#+END_SRC

Here I setup the org project association lists. I have 3 kinds of pages on my
site; I call them "notes," "pages," and "static" assets. All of the settings
here can be found in the [[http://orgmode.org/manual/Publishing.html][Publishing section]] of the orgmode manual.

#+BEGIN_SRC elisp :tangle ~/.emacs.d/private/bsima/config.el
(setq org-publish-project-alist
      `(("org-notes"
         :base-directory "~/me/notes/"
         :base-extension "org"
         :publishing-directory "~/me/www/public/notes/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 5
         :html-head ,bs-site-head
         :auto-preamble t)

        ("org-pages"
         :base-directory "~/me/www/resources/pages/"
         :base-extension "org"
         :publishing-directory "~/me/www/public/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 5
         :html-head ,bs-site-head
         :auto-preamble t)

        ;("org-essays"
        ; :base-directory "~/me/essays/"
        ; :base-extension "org"
        ; :publishing-directory "~/me/www/public/essays/"
        ; :recursive t
        ; :publishing-function org-html-publish-to-html
        ; :html-head ,bs-site-head
        ; :auto-preamble t)

        ("org-static"
         :base-directory "~/me/www/resources/assets/"
         :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
         :publishing-directory "~/me/www/public/assets/"
         :recursive t
         :publishing-function org-publish-attachment)

        ("org" :components ("org-notes" "org-pages" "org-static"))))
#+END_SRC

To actually publish everything, I need to do =M-x org-publish-project RET org
RET=. That's too many things, so here is a helper function. The =t= makes
orgmode publish everything, even if the file's been unchanged.

#+BEGIN_SRC elisp :tangle ~/.emacs.d/private/bsima/config.el
  (defun bs-publish ()
    (interactive)
    (org-publish-project "org" t))
#+END_SRC

*** Tasks

I keep my tasks in =~/Dropbox/org/tasks.org=. The value of =bs/tasks-file= is
where my tasks live, and the function =bs/get-tasks-file= will open my tasks in
a new buffer.

#+BEGIN_SRC elisp :tangle ~/.emacs.d/private/bsima/config.el
(setq bs/tasks-file "~/Dropbox/org/tasks.org")

(defun bs/get-tasks-file ()
  (interactive)
  (find-file bs/tasks-file))
#+END_SRC

To view my tasks, just do =SPC a t=.

#+BEGIN_SRC elisp :tangle ~/.emacs.d/private/bsima/config.el
(evil-leader/set-key "at" 'bs/get-tasks-file)
#+END_SRC
