* Wonder and Desire in Romantic Love: A Levinasian-Irigarayan Analysis

Perhaps no concept is more pondered about than love. It sits in the back
of the mind as one decides how greatly to involve oneself in the lives
of others. It surfaces in a hot pressure when one idolizes another
before one really knows why. It often seems that one cannot know how
profoundly love affects decisions, actions, and thoughts, nor can one
know the nature, origin, or rationality behind the love sentiment felt;
it is relegated to a mysticism. I would like to argue otherwise: love is
an intelligible concept when subjected to phenomenological analysis.
While much of the question of love is wrapped in mystery and wonder,
this does not preclude it from analysis; indeed, love has been analyzed
since the time of Plato's /Symposium/, and it holds a special importance
in the philosophies of Emmanuel Levinas and Luce Irigaray.

Typical analyses of love have divided the concept into three or more
types: /agape/, or compassionate love; /eros/, or sexual love; and
/philia/, or preferential, friendly love. I will discuss /romantic/
love, a definition of love that is similar to /eros/ but goes beyond
mere physicality. Romantic love requires both phenomenology and ethics
as it consists of a dynamic movement between the infinitude of the other
and the intimacy of the self. Levinas attempts to establish a new
phenomenologically-based ethics of otherness and infinity, an ethics
that is grounded in the phenomenological experience of the self and the
other. He provides a framework from which one can analyze the so-called
mysteries of love. Irigaray explains how sexual difference is
fundamental to the organization of relationships, and gives a practical
foundation for moving beyond stereotypical gender roles. She allows the
ground for applying the Levinasian framework to the biological and
sexual reality of relationships with significant others.

Additionally, Levinas and Irigaray have a unique relationship in that
they are gender opposites analyzing sexual differences and the
relationship between these differences. Each is limited by their sexed
and gendered condition, but contributes what the other is lacking:
Levinas gives the male interpretation, and Irigaray the female. By
understanding the work of each thinker and considering them together,
one may begin to build the new ethics that each thinker wanted.

After recounting the ethical and phenomenological situation that Levinas
uncovers (and with which Irigaray will largely concur), I will argue
that the passion of wonder should have a fundamental role in all
analyses of ethics and love. I will show how wonder can uphold
difference in the romantic-erotic relationship, change the way the ego
relates to the other, allow for the persistence of love over time, and
enhance the dimensionality experienced by the self as it illuminates the
infinitude of the other.

I will proceed with a definition of difference that includes both
ethical alterity and sexual difference. I will also take up Levinas'
definition of ethics as a layered experience of the relationship with
the human other (intersubjectivity) as it relates to a person's
interiority and exteriority. [1] Levinas' ethics is important because it
maintains a sense of the “height” of alterity, from whence desire and
infinitude originally come. Irigaray's analysis of wonder and sexual
difference converges with Levinas' framework and helps to explain the
unique intimacy felt in romantic relationships. However, before one
understands how wonder, desire, and infinitude work, one must understand
how the ego and the self relate to the world by itself.

** Knowledge and Totalization

The self first relates in habitation. One is “at home” with ones' books,
one's knowledge and experiences or memories, and the work one does for a
living; the self creates for itself a habitation, defined as the
“utilization of an ‘implement' among ‘implements.'” [2] In understanding
the world, the self experiences things outside of itself through itself;
that is, one comes to understand the world only through the subjectivity
of the self. No other perspective is possible except the perspective
/from the self/---and so one begins from the habitation of the self and
moves outward in understanding.

The process of this movement is performed by the ego. In this process of
moving outward, the ego understands the world by creating an adequate
world within itself. For each object it comes across, a representation
of the object is created in the self in the way that the ego encounters
it. That is, the object in representation undergoes a process of
adequation in which it is constructed within the self, by the ego. The
objects of the ego-self's mental representation of the world must be a
reduced version of the real object because it is interpreted according
to the ego's perspective of it: this constitutes the limits of
subjectivity itself. It is the ego that performs this adequation as it
goes out to the world, recognizes an object, understands the object, and
then returns to the self with the representation of the object for
further cognition.

In this way the ego distinguishes for itself two phenomenological
realms: the interiority, the mental construct of the ego which is a
representation of the world that references the self in that it is an
adequation of the external world to the self; and the exteriority, the
physical habitat of the individual which is made up of implements that
serve as the exterior dwelling place of the human. Consciousness then
occurs within the nexus of interiority-exteriority: “consciousness of a
world is already consciousness /through/ that world.” [3] Interiority is
the purely mental of the individual, exteriority the purely physical.
Within interiority can only reside known objects. While exteriority can
hold objects that the ego has known via its process of adequation, there
also exist objects unknown, objects that are entirely /other/ than the
self. These “others” are what the ego seeks out to know and understand.

As it moves outward in understanding, the ego performs an adequation
between exteriority and interiority. For each object that the ego
understands, it could be said that the ego expands to encompass said
object as an addition to its interiority. It is important to note that
this clear distinction breaks down at a certain point of reasoning
(which I will show later as the threshold of the other); its purpose is
to help one understand the underlying forces at work which give rise to
our lived phenomenological experience. As Levinas says, “The ambiguity
of the body is /consciousness/. There therefore exists no
/duality/---lived body and physical body---which would have to be
reconciled. The dwelling which lodges and prolongs life, the world life
acquires and utilizes by labor, is also the physical world where labor
is interpreted as a play of anonymous forces.” [4] The terms selected
for this discussion---interiority and exteriority---are used by both
Levinas and Irigaray. While the Cartesian tradition serves as an
important inspiration for both thinkers, these terms do not split the
human being; they simply describe two “worlds” or places in which the
self experiences and relates, in which the ego operates. Levinas in fact
escapes Cartesian solipsism through the face-to-face relationship, in
which the self encounters the other. But that relation is only the
second relation, because it only exists as the self moves outward from
itself and the relationship it has with itself.

This first relation---that is, habitation---is one of pleasure. To
understand pleasure in the context of habitation, one must acknowledge
the privileged place of the home in human life. The home is more than
just a shelter; it is a place to which one may return in comfort and
enjoyment, a sanctity for the self. The home is the “tool” that allows
for the creation of habitation. The pleasure that a human derives from
his or her home highlights the pleasure drawn from habitation, or
rather, the pleasure that comes from using an “‘implement' among
‘implements.'” [5]

As one moves outward from the dwelling place (both the mental and the
physical), the ego expands to relate to its surroundings through itself.
“Simultaneously without and within, he goes forth outside from an
inwardness [/intimité/].” [6] In understanding, the ego totalizes the
world around it and wraps the world within itself, self-identifying with
the knowledge-base it creates as it moves through the world and
organizes the elements of the world. Herein the self creates for itself
an “insular sufficiency”---the Levinasian term that describes the self's
relation to itself. The self creates its own happiness within itself, at
home with itself, within its own habitation---it is truly
self-sufficient.

Insular sufficiency is a totality among totalities (or, a finality among
finalities). It is not, perhaps, the grand totality of knowledge
envisioned by positivism or of Spirit by Hegel, but it creates a
physical and mental home for the ego and in the image of the ego. During
this act of creation, the ego is projected onto the world physically and
mentally. The ego thus /enjoys/ the world it has created; it derives
pleasure and comfort from its home. In its home, it is the master of its
implements, all of its needs are met; and if it happens that one need is
not met, the ego does what it must to fill the need. Levinas writes:
“Thus I can /take pleasure/ in handling a tool, in working, in
accomplishing, using gestures which, to be sure, fit into a system of
finality, but whose end is situated beyond the pleasure or pain procured
by these isolated gestures themselves, which fill or /nourish/ a
life.” [7]

This insular sufficiency is in fact an /enjoyment/, and perhaps the
greatest enjoyment the self could achieve, because it /nourishes life/,
it promotes the continuation of life into the future. “The human being
thrives on his needs; he is happy for his needs.” [8] The satisfaction
of, say, post-meal satiation is more than a physiological mechanism, it
is a sublime pleasure. It is the mastery in needs of the self that
completes the insular sufficiency: “not a mastery on the one hand and a
dependence on the other, but a mastery in this dependence.” [9] Such is
the self-sufficiency of the separated and enjoyed self: an apparent
paradox of the mastery in dependence [10] of one's needs.

I would like to extend and emphasize that the self's needs are
inherently biological simply from the fact that human beings are
situated in biology. This biological situation is an important point
that will come up later. Irigaray wants to emphasize the biological
dimension of the individual, as evinced in the title of her work, /The
Ethics of Sexual Difference/, "sexual" here referring to the biological
phenomenon. And while biology is not a chief concern for Levinas, he
does emphasize the physiological source of our needs.

From this rather simple and basic framework, one can derive a few
important distinctions. The “self” and the “ego” must not be construed
as the same. Instead, one must understand the ego to be an element
within the self, a device for the self's cognition. The self is the
individual, the biological identity of the (human) subject. I do not
assert that the cognitive action of the self occurs in the mind, the
body, or in otherwise separate processes. Suffice it to say that the
self contains the ego and all other things that an individual would
claim ownership over via a synthesis of interiority and exteriority. The
self creates a cognitive framework in which the ego may recognize
(re-cognize) self from non-self, in which the ego may create its home,
thereby completing the individual's identity in what Levinas calls the
“I.” [11] The ego moves outward toward the world in understanding,
making the world adequate to it and reducing the other to the same. Thus
is the ego the totalizing element within the self. In order to totalize,
the ego must be self-referential: it must return to itself in its
process of adequation. In this way, the ego assumes a teleological
structure.

To return to the main point of this section---that is, to describe the
first relation as one of habitation: The /mental home/ of the
individual's ego and the /physical home/ of the dwelling place of the
human are indeed the same in that they provide a pleasure, completely
derived from the self and the immediate external world, and contribute
to insular sufficiency: the ego's mastery of its mental and physical
surroundings.

The expansion of the ego is not in itself “good” or “bad.” The human
/relies/ on the ego for a great many tasks insofar as the ego is a
device of cognition employed by the mental faculties. What is “good” or
“bad” is decided in part by the bounds of the ego's totalizing movement.
I will now investigate the bounds of the ego in consideration of the
ethical relationship with the other.

** The Ethical Relationship

#+BEGIN_QUOTE
  Multiplicity in being, which refuses totalization but takes form as
  fraternity and discourse, is situated in a “space” essentially
  asymmetrical. [12]
#+END_QUOTE

There is the other that needs to be addressed when considering the
totality of the ego. I have stated that first the ego expands to
encompass the world in its knowledge-gathering totalization, but I have
not discussed the possibility of alterity.

As the ego expands and progresses toward totality, it necessarily
relates everything to itself; that is, it reduces other things to the
same as itself so that it can understand them. However, there is an
event in which the ego comes upon that which cannot be reduced to the
same. The term Levinas uses to refer to that which cannot be reduced to
the same is “the other.” The other is characterized by /alterity/, or
otherness. “The absolutely other is the Other,” that is, the other
person. [13]

The first encounter the self experiences with veritable alterity is the
face of the other. [14] The face of the other is not just a human face
like one's own that is recognized as similar. The face constitutes both
sight and sound---it is more than merely the representation of the human
face: the face of the other also /speaks/ to the self in the sense that
the other announces their appearance in their infinitude. The other
cannot be announced in just sight, for sight is too structured and
apparent [15]; it again relates to the cognitive movement of the ego.
There is no “recognition” of the face of the other; it does not even
refer or relate to the ego's movement of totalization. The face reaches
past the emergence of the ego. This goes beyond sight and introduces an
ethical command at the level of the senses of the self, pure
sensibility; it therefore escapes totality. Levinas likens this ethical
command to the religious commandment, “Thou shalt not kill.” [16]

Levinas describes the primordial relationship of the self to the other
in phenomenological terms. He examines the minute, instantaneous,
perhaps somewhat hidden experience of the self as the other approaches
or confronts it. The /first/ thing to come from the other, then, is this
commandment: do not kill. Generally taboo in everyday life, killing and
death strike a primal chord when reflected upon, and Levinas explicates
the reason for this. The self's first concern is self-sustainment and
survival; its first enjoyment is the self-sufficiency derived from its
survival. The confrontation with the other, then, would typically be
seen in either of at least two ways: a reciprocal display of empathy for
the shared subjectivity and self-sufficiency of the other (“You are also
a living subject, first concerned with your own survival; this I
understand and will respect by refraining from murder.”), or an
understanding of the other as non-threatening (or non-essential to the
self's survival) and thus not worth the effort of murder. However, both
of these interpretations are self-referential and assume a cognitive
understanding of the other, thus they reduce the other to the selfsame
and are representative of the ego. This understanding of the other is
one in which the absolute alterity of the other is filtered and consumed
via the totalizing tendency of the ego. Here, the ego assumes a
totalitarian control over the self's exteriority. In opposition to the
above egoistic ethics, Levinas explains that the ethical command
necessarily /comes from the other/ [17] and therefore does not subscribe
to an egoistic interpretation of the other's appearance. Rather, the
ethical command cuts across the ego's totalizing movement and announces
itself within the fundamental constituent of the self, the most
primordial part of the identity.

Take the following example of the ethical command: In a confrontation
such as a robbery, a gunman sets his sights on a target. But as he lays
his eyes on the face of the other---the face of his target---he
recognizes a sense that calls out to him, within him, and commands him
to not fire his gun, to not kill. This “sense” is not a logical
formalism or otherwise an act of logical volition; rather, it arrives at
a much more fundamental and visceral level, even before logic and
reason. It comes from outside, but is realized as an interior
feeling, [18] as a conscience dictating how one should act from the
other. This command requires a response. In the example above the
response is to not fire the gun. This response is constituted as
responsibility (response-ability). The ability to respond to the ethical
command of the other is what creates the ethical relationship, the
intersubjective space between the self and the other.

A negation of this command is possible, which is the first violence that
one person can wage on another. Violence begins when the self attempts
to understand the other, to wrap the other in its cognitive structure,
to allow the ego to violate the bounds of the other; the ultimate extent
of this violence is when the self murders the other. This violation
reduces the other to something /known/. Levinas understands this
violence as θεωρία, or theory. To theorize about the other as the first
and principal way of relating presupposes knowledge of the other; it
includes anticipation and assumption, which necessitate a reduction of
the other to what can be known. This reduction of the other to the same,
to knowledge, is a refusal to respond to the ethical command of the
face; it is an overpowering of the other, rather than a respect of the
other's alterity. This propels the ego to a position in which it
believes it can treat the other as a known object, an implement within
the expansion of its habitation. While this sort of objectification
cannot /truly/ occur, the ego /believes/ that it can, and acts as if it
has. This is a necessary result of the way that the ego proceeds to
understand the world in a totality.

The task of ethics is to resist this reduction and overpowering of the
other by the ego. For Levinas, ethics does not propose or discuss values
(utilitarianism), virtues (virtue ethics), or universal rules
(deontology)---all of these assume a certain ontology of the other.
Instead, ethics must respect the infinite difference as a “height”: the
other is situated infinitely higher than the self, out of reach of the
self's totality, in a "'space' essentially asymmetrical." [19] This is
what is meant by the asymmetry of the ethical relationship.

** Desire for the Other

Levinas claims that there is something that produces the “movement going
forth from a world that is familiar to us,” which leads to the
integrating structure of the ego, and this production is desire. [20]
This is a desire defined differently than in the past, as Plato and
others defined it. This is a metaphysical desire, which produces the
nourishment of life beyond the satisfaction of one's needs. It pushes
the self past mere survival and into enjoyment, it drives one to /move
beyond/ the limitation of the “ipseity of the I,” as Levinas says. It
does this by producing its own hunger; indulging in its satisfaction
only deepens the desire.

Typically, desire has been predicated on a lack. The subject is
incomplete, and thus yearns for something else. The subject's aim thus
becomes the acquisition of something: this is the acquiring definition
of desire. The productive definition of desire is the metaphysical
desire; Levinas terms these “need” and “desire” respectively. In a
sense, metaphysical desire produces the desire we feel to satisfy our
needs.

I will again assert a biological basis for this production of desire.
The double-act of desire is that it satisfies and produces: desire-need
(or, the archetypal definition of “desire,” from here on simply termed
"need") satisfies needs reducible to physiochemical ratios, needs for
which the ego is the active element in finding satisfaction. This need
is predicated on acquisition: the self lacks something, and the ego is
activated to find a satisfaction for the need. This kind of need is
analyzable by scientific reductionism, every need understood as a
chemical process or psychoanalytic complex. Thus every biological /need/
can be reduced to a physiochemical ratio and, if one so pleases,
satisfied artificially. But this does not say anything about the
phenomenological experience of desire. A metaphysical desire cannot be
predicated on a lack because its logic is too easily reduced to a
physiochemical ratio. On the other hand, “the metaphysical desire has
another intention; it desires beyond everything that can simply complete
it.” [21] Metaphysical desire produces one who mires in enjoyment and
/nourishment/ of its enjoyment, that first relates to this enjoyment and
as such announces its existence. Indeed, desire /procures life/ in
nourishing and announcing its own existence. Desire throws the self into
life and toward the Other.

The situation of need and desire [22] in the trough of our biological
existence indicates that difference is fundamental, not attributable, to
the biological. The notion of biological difference will be clearly
explicated in further analyses. Irigaray's claim is thus accurate in
that it places an ethical difference of love and a bigendered society in
sexuality, a property of biology.

** An Ethic of the Sexual

From the description above, it could seem that Levinas' work is simply a
phenomenological description of Platonism. In a sense, Levinas is
putting forth a radical rereading of Plato. As Plato originated the
tradition of the opposition between theory and practice within an
integral structure (which I have been calling the ego), this dichotomy
“will disappear before the metaphysical transcendence by which a
relation with the absolutely other, or truth, is established, and of
which ethics is the royal road.” [23] Levinas' analysis precedes reason;
it undercuts θεωρία, and describes a relation that cuts across the
reasoning faculties of the ego which are categorized as theory and
reaches to the fundamental /desire/ that nourishes existence and thus
produces it. While Plato studied the /being/ of existence, Levinas gets
at the /becoming/ that produces being.

But where is one to find this “metaphysical transcendence” and resultant
desire that allows one to traverse the royal road of ethics? Levinas
would say it is precisely alterity that leads us down this road.
However, it could be argued that the alterity that Levinas supposes as
fundamental is actually just a self-deception, as if Descartes' demon is
telling the self that the other /actually is/ alterity, thus tricking
the self into responsibility for the other because it is ultimately in
the self's rational best interest to be responsible for the other. [24]
But Levinas does not posit a rational self, he posits a passive and
ethical self; to posit a rational self would undermine Levinas' ethical
structure of alterity and consume the other in θεωρία: it would become
an ethics of violence. The task for Levinas, then, is to maintain a
pluralism that can allow for the alterity that leads to metaphysical
desire. He typically achieves this by discussing the metaphysical
“ipseity of the I” which is the mode of enjoyment that the self derives
from its egoist existence, nourishing itself in its needs. This egoist
existence implies a separation from the society: egoism begets
pluralism. When Levinas discusses pluralism, he does so
phenomenologically: “Pluralism is not a numerical multiplicity.” In
order to realize pluralism, “there must be produced in depth the
movement from me to the Other.” That is, “pluralism implies a radical
alterity of the other,” constituted in the intersubjective relationship
wherein I “/confront/ [the other] out of my egoism.” [25] But then, in
the same paragraph, Levinas says, “Sexuality supplies the example of
this relation... the other sex is an alterity borne by a being as an
essence and not as the reverse of his identity; but it could not affect
an unsexed me.” At times Levinas seems to maintain that alterity is a
purely metaphysical phenomenon, derived from the fact that the self is
separated (the “ipseity of the I”) and then encounters the face of the
other which begins relationship; but here he says that alterity “could
not affect an unsexed me,” which refers to the sexuality of biology. In
fact, this indicates the heart of Levinas' struggle with romantic love:
even though one's identity is so grounded in one's biology, Levinas does
not want to reduce romance to a biological relationship, which implies
that love is nothing more than the physiological need for sex. Instead
he maintains that love must be altruistic and agapic: it can only be
metaphysical.

This presents a problem for romantic love. How can lovers embrace in
their erotic drives while still maintaining an ethical sensibility? Can
an ethical love be compatible with physical love? Not according to
Levinas, it seems, but even he ends his first /magnum opus/ with an
essay on “The Phenomenology of Eros.” If desire throws the self toward
the other, and the ego wants to totalize the external world, how does
one avoid violating the other in θεωρία? How can the self uphold the
infinite alterity of the other, while still allowing the ego to satisfy
its need to totalize the other in the satisfaction of its erotic and
bodily needs? In fact, when the passions of desire and wonder are
analyzed, it is shown that romance as a biological relationship /does
not/ imply simply a physiological satisfaction of needs; it is much more
than that. Uncovered is a profound experience of intimacy at the
threshold of the other. The mistake Levinas makes which blinds him from
seeing this analysis is a misunderstanding of sexuality and gender and
the essential difference that both indicate. The backbone for this
analysis is provided by Irigaray.

In the final sections of /Totality and Infinity/ is “The Phenomenology
of Eros,” regarded as one of Levinas' most complicated pieces. He
analyzes the erotic encounter with the “Beloved” by discussing wanton
nudity versus erotic nudity, immodesty versus modesty, and carnality
versus the tenderness of the loving caress. The caress “/searches/” for
the other in love: “In a certain sense it /expresses/ love, but suffers
from an inability to tell it.” [26] In caressing the other, the lover is
animated with love, but they cannot reduce their feeling to mere words.
(Is it any wonder that poets have struggled to tell of love for so
long?) The animation of this love does not move toward knowledge as the
ego does. Rather, the caress searches for “what /is not yet/, bringing
us back to the virginity, forever inviolate.” In the erotic encounter,
the caress is oriented toward that which “/is not yet./” [27] Sex as
lovemaking, as an extension of the caress, relieves the self of the
weight of its existence in the present moment by exposing the self to
the /not yet/. In sex as lovemaking, as opposed to sex as instinct,
there is no anticipation of a future determined. It does not refer to
the possible as freedom, in which one could rationally choose one
possible over another, as in the case of the face-to-face which opens
the self to the light of reason. “/Eros/ hence goes beyond the face,”
and beneath the reasonable other. [28] It gets at the other's
hiddenness, the secrecy of their interiority. /Eros/ does not know the
other's secret, it only senses the presence of the secret, it touches
the other's secret without the need to understand it. Each lover refuses
to surrender themselves at the primordiality of themselves as a
non-existent---a refusal to objectification---instead they choose a new
direction for both as a direction toward intimacy, a “dual solitude,
closed society.” [29] This is the way of the caress in lovemaking and
voluptuosity: it is pure experience, pre-concept. There is no meaning to
be found, no light to be seen, and no explanation needed.

As Levinas continues his line of thought, he makes two mistakes in his
analysis. “If to love is to love the love the Beloved bears me, to love
is also to love oneself in love, and thus to return to oneself.” [30]
But this sentence describes the same self-referential structure as the
ego. The end of /eros/ is the love of the other and hence the love of
oneself, for Levinas, and the manifestation of this end is the child:
the creation of another self, the progeny. But this not only reduces the
other to the same, it reduces the /progeny/ to the same as well. At the
beginning of his essay, Levinas says, “To love is to fear for another,
to come to the assistance of his frailty. In this frailty as in the dawn
rises the Loved, who is the Beloved. An epiphany of the Loved, the
feminine is not added to an object and a Thou antecedently given or
encountered in the neuter (the sole gender formal logic knows). The
epiphany of the Beloved is but one with her /regime/ of
tenderness.” [31] Levinas here rather explicitly names the loved other
as the Beloved and as the feminine. “And the other whose presence is
discreetly an absence, with which is accomplished the primary hospitable
welcome which describes the field of intimacy, is the Woman.” [32]
Levinas sees the woman and the feminine as the dwelling place to which
/eros/ eventually aims and which begets the progeny. But this
presupposes the other as a means to the erotic end; that is, it rather
blatantly objectifies the woman as a means for procreation and as a
place for the erotic needs to be satisfied. The intriguing aspect of
Levinas' treatment of /eros/, however, is not how he uses the term
“femininity,” but how he defines it. Throughout his essay, Levinas does
not objectify the Beloved; in fact, the Beloved refuses surrender
completely. [33] Objectification is only possible when “Woman” and
“feminine” are defined as a /type of personhood/, i.e. a gender, thereby
categorizing persons according to a norm and removing their
individuality. But Levinas does not define either in this way. For
Levinas, the feminine is simply the welcoming of the other's hidden
secret as it is presented to the self. As a man, Levinas can only
understand the feminine in this way. If his essay is re-read with
“feminine” replaced by a more appropriate term (such as "sexual-other"),
his analysis still holds without objectifying woman. The unfortunate
naming of other-welcoming as feminine is the first mistake Levinas makes
in his analysis of /eros/. The second is to mark the end of /eros/ as
the progeny. With the progeny as the /telos/ of /eros/, romantic-erotic
love can only be reductionist. In this way, /eros/ maintains a primarily
egoist and physiological structure. Levinas cannot break out of the
totalizing, teleological structure he set up for himself at the
beginning of his essay by explicitly naming the other-welcoming as
feminine and the /telos/ as progeny. Without this distinction, if the
hidden other and their welcoming of the self is understood as simply
sexual difference, then /eros/ does not need to take any object at all.
In fact, the erotic experience /cannot even/ take an object, because it
exists in a realm without knowledge, without the egoist need to know.

It is true that this teleological form of /eros/ conforms to what can be
construed as a masculine logic. This line of thought has been taken up
by Irigaray in studying the typical sentences constructed by "certain
groups of neurotics (and which of us is not neurotic?)" and reported in
/An Ethics of Sexual Difference/ (interjections in brackets are mine):

#+BEGIN_QUOTE
  The typical sentence produced by a male, once all substitutions have
  been allowed for, is:

  /I wonder if I am loved/ or: /I tell myself that perhaps I am loved./

  The typical sentence produced by a woman is:

  /Do you love me?/

  In the first case, the utterance circles back to the speaker with the
  almost constant wariness of a /doubt/. The subject speaks to himself.
  Doubt is often the only weak point in the bubble in which he is
  situated and enclosed [that is, his ego]. No place for the words for
  the other here. The message is reflexive, reflects back to the one who
  produces, or reproduces, it. The medium, the imagery of the message is
  so closely involved with the speaker that should another person, male
  or female, wish to try to listen, even without being invited, he or
  she would have great difficulty understanding what is being said.

  The other is excluded from the communication in two ways: as speaker
  and as listener; the other can only shout an appeal or ask a question:
  /do you love me?/ (correlative to /who am I?/). The interrogative form
  presents the message as ambiguous, incomplete. The /yes/ or the /no/
  of the (you) underlies the meaning of the utterance, and the only
  subject of utterance here is the person addressed. The subject who is
  apparently producing the message occurs only as the possible /object/
  of the person addressed, an object that is no longer a point of
  convergence for the protagonists of the utterance, an object of
  exchange, because the only subject is (you).

  These two types of utterances are incomplete from the point of view of
  both addressor and addressee, and they raise the issue of the
  differentiation of the poles of utterance. For the (I) and the (you)
  are distinct from one another in function of a singular reference to
  the world, and they "divide" up the world, but in a way that hinders
  communication. [That is, for the sexual subject, the world is /already
  divided and separated/; it cannot be brought back together with
  language or any other grammar.] They represent two unequal parts of
  the world that are capable neither of exchange nor of alliance. A kind
  of original symbol that has been badly split and which deteriorates
  into various pathologies as a result of that badly managed separation
  or fission.

  This leads to social crises, to individual illnesses, to schematic and
  fossilized identities for both sexes, as well as to a general
  sclerosis of discourse, a hardening of language and a repetitiveness
  that makes nonsense of established meaning. Inflation and devaluation
  afflict a semantic system installed in a position it refuses to
  question. [34]
#+END_QUOTE

The whole of this section is to point out that any attempt to reconcile
the fundamental difference of sexuality by appealing to language---or
any other formal structure, for that matter---is inadequate. An ethical
love between two must cut beneath this formal structure, it must resist
a reduction to the quantitative. For if love is approached via a formal
method, the "social crises" of sexual identities will never be overcome
and /both/ sexes will be subjugated to "fossilized identities." Thus,
the animations of love cannot be per-formed or written down, rather they
must be improvised, spontaneous; neither can they be communicated in any
linguistic manner, but only expressed as a sensible quality to be
accomplished by the other.

An analysis of the male sentences Irigaray provides shows that
"masculine utterances have generally been transformed into /the third
person./" [35] The /I/ of the masculine subject is transformed into a
/he/, a projection of the male image, through the form of language. As a
transposition of /I→he/, the formalism of language masks the subject by
and in the construction of a world, the construction of a truth. But
one's thinking---thought, θεωρία---takes place /in language;/ thus
language subjugates rational thought itself. [36] Language /forms/
thinking into truth; a construction of the abstraction of truth by
formalizing the chaotic world into ratios of known quantities: man
constructs truth in his language. But this truth-structure of language
loses "its propriety once there is the slightest degree of pathology in
the subject." Pathology reveals the hidden drama which founds linguistic
utterances and the truth-form which they assume. Thus linguistic truth
is tautological: "the redundance of the /I/ on the 'masculine' side and
the circularity of the process of utterance constitute the world in a
tautological circle."

But this is still only a masculine language, it can only constitute a
masculine world. Mankind must step outside of his tautological circle
and into a new world entirely if he wishes to make progress; to "remold"
the world into "a new era in history." [37] If this tautological
language is indeed sexed, as Irigaray has shown, then no doubt the
sexual-other is the "new world" which man must pursue. But woman has
historically been assigned specifications by man: to a role of
"/reproduction/, as a maternal machine designed to have babies;" as a
/guardian of the dead/, to watch over man's desire for continuation in
the form of immortality and the resurrection of his identity, the return
to his identity; as a /mechanical doll/ for lovemaking, who's
seductiveness is a public display of a private performance; to /the
goddess/, as an inscription of man's and mankind's fantasies (generally
conscribing of the above three specifications).

To arrive at the new world which is the sexual-other, man must desist
from assigning woman to any of these specifications. "Perhaps man might
then discover that something of another world persists in the female.
Something that lives... Immanance, in-stance in the feminine?" [38] But
man is already instantiated in himself. It would take a radical event to
remove him from his body, to have an event of ec-stasy coupled with an
in-stance of the sexual-other. To this effect, the Levinasian caress is
not enough. Levinas takes the loving caress to the edge of the masculine
ego, the edge of the tautological world, with every intention of
approaching the new world. But then he stops, and turns back in the name
of self-love and the progeny. For if Levinas loses himself in the other,
how is he to produce a child who is both himself and a stranger? [39]
His logic doesn't allow for a crossing of the threshold toward the other
because doing so would undermine his method for reproducing his identity
in his progeny. What is needed, then, is a new method of producing
identity constituted in the subjective experience of space and time
which can be reconciled at the threshold of the sexual-other. A method
that is not formalized into a technique to be performed for a
pre-determined outcome, but a way or a path to be re-invented at each
conception, re-experienced anew at each event, de-constructed and
re-constructed at every encounter. If the ego constructs a world out of
the same as I have discussed, then the way to the sexual-other must
circumnavigate the ego and it's sameness; or, perhaps the sexual-other
must /alter/ the ego.

The pure experience of the caress can be described as an enjoyment, but
it is an enjoyment distinct from the satisfaction derived from the ego
as the “ipseity of the I,” for in the act of lovemaking, “every subject
loses its mastery and method.” [40] Without the mastery of the I,
freedom does not even make sense. No choices or determinations can be
made, nor need they be made, because the pure experience of desire
overwhelms the self. Within this overwhelm, there is no room for the
ego. Instead, the passions of desire and wonder consume the self and
condition the subjective experience of space and time. Wonder is the
missing element in Levinas' analysis.

** An Aside Concerning the Philosophical Relationship Between Irigaray and Levinas

Before continuing with my discussion of wonder, it is important to
clearly lay out the relationship between Irigaray's thinking and
Levinas'. Even though Irigaray often writes with a critical pen toward
Levinas, his ethical thinking (specifically, his concept of the Other)
is central to her ethics of sexual difference. Elizabeth Grosz even
states that "Levinas' conception of alterity is central to Irigaray's
understanding of relations between sexually different subjects." [41]
The unique concept of alterity that Levinas relies on is a "revival of
Hebraic thought repressed by the Greek logocentric tradition, which
Irigaray employs to articulate an ethics of sexual difference." [42] So
in this sense, Irigaray is indebted to Levinas' ethical thought. In
traditional ethical theory, the subject is construed as gender-neutral,
abstracted from any kind of embodiment or real-world experience. Recent
analyses show this neutrality to be only a façade for masculinity. [43]
However, the ethical subject of which Levinas writes /is/ masculine: the
subject is "virile" and "heroic." Said embodiment of the ethical subject
in Levinas' thinking is a step in the right direction, but the subject
is still only masculine. Irigaray's critique enters the picture when
Levinas names the feminine as (according to Irigaray) the Other of the
Same, which Irigaray claims is simply the negative of man: "The
feminine, as it is characterized by Levinas, is not other than himself.
Defined by 'modesty', 'a mode of being which consists in shunning the
light' ... the feminine appears as the underside or reverse side of
man's aspiration towards the light, as its negative." [44]

While Irigaray provides a powerful critique of certain aspects of
Levinas' thinking, the case can be made that Levinas' characterization
of the feminine is neither a Manichean-like dualism, nor a Lacanian
"Other of the Same." [45] Levinas does not deny that the encounter with
the feminine is still a face-to-face relationship, even if it does go
beyond the face. This face-to-face relationship can be described as
non-negative precisely because it is untotalizable: "if the constitutive
terms of the relation could be characterized as positive and negative,
they would in theory be able to fuse and cancel each other out, in much
the same way as a proton and an electron do in physics." [46] The
Levinasian term that indicates Irigaray's confusion is "dialectic."
Levinas writes, "The force of opposition and of dialectical evocation
would, in integrating it into a synthesis, destroy transcendence." [47]
The definition of "dialectic" that Levinas uses is not a Marxist method
of dealing with contradictory forces, nor the Hegelian historical
resolution of contradictions. Rather, it is closer to the Platonic sense
of investigation via discussion. [48] Therefore, Levinas' feminine is
not simply non-masculine, but rather is outside of the binary
masculine-feminine dichotomy. Instead, Levinas employs the metaphors of
darkness and the nocturnal which are aligned with the feminine against
the metaphors of light, openness, and frankness which describe not the
masculine, but the face: "The face signifies by itself... A meaningful
behavior arises already in its light; it spreads the light in which
light is seen." [49] This particular employment of metaphors has the
potential to deconstruct the male/female binary and posit a new terrain
of metaphors, which is the same goal toward which Irigaray works. In
fact, when taken in concert, the two essays "Phenomenology of Eros" and
"Fecundity of the Caress" are a powerful example of the deconstructive
form of writing, and together they unearth a new concept of an ethical
erotic.

For Levinas, /eros/ can never accomplish a union between two lovers;
the caress never truly touches the other. "Neither is the difference
between the sexes the duality of two complementary terms, for two
complementary terms presuppose a preexisting whole. To say that sexual
duality presupposes a whole is to posit love beforehand as fusion. The
pathos of love, however, consists in an insurmountable duality of
beings." [50] Instead, the caress describes precisely the failure of
erotic communion, and instead is redirected toward fecundity: "the
caress consists in seizing upon nothing." [51] Whereas the caress is not
teleological, /eros/ is whence it creates the progeny. Here the
distinctions between voluptuosity and fecundity are clear: the
non-teleological caress is voluptuous, but fails to establish a
relationship with the sexual-other; fecundity must then take the reigns
and establish a connection through the progeny. "The carnality of
voluptuosity gives way to the spiritual love evinced in the father-son
relation. 'Pure eroticism,' and all this expression could imply about
desiring flesh, gives way to 'sentimental love'" for the child. [52] In
doing so, patriarchy emerges as the oppressor of voluptuosity, and
/eros/ becomes teleological.

For /eros/ to be teleological, the feminine must be passive in order to
take on the transformative power of fecundity and eventually lead to
what Levinas calls transubstantiation. To this aspect Irigaray gives the
harshest of her critiques, and rightly so. For Irigaray, the passivity
of the beloved subject has its own power which animates and transforms
the sexual-other from the beloved into the lover. Instead of fecundity
completely wrapped up in the masculine, as it is in Levinas' thinking,
Irigaray claims that the feminine has its own fecundity: "Intimately
tied to universal circulation and vibration that go beyond any enclosure
within reproduction. Turning in a cycle that never revolves back to
sameness. Continual and patient engendering of an obscure labor. More
passive than any voluntary passivity, yet not foreign to the act of
creating/procreating the world." [53] Thus there is some kind of a
communion of (pro)creativity between the sexes. This creativity and
fecundity takes the form of a revitalization-between instead of a
teleological act for some other purpose. "Fecundity of love between
lovers---the regeneration of one by the other, the passage to
immortality in and through the other---this seems to become the
condition of procreation and not a cause in its own right." [54] Thus
the progeny is not the /telos/ of /eros/; rather it is the condition of
sexual (pro)creation.

 According to Irigaray's critique, the child must not be seen as the
creation of an immortal exteriority by the lovers. Rather, the child and
the concept of the progeny must be a path ("chemin") between the
lovers. [55] But before the path can be laid, there must be a dimension
in which it may be sketched out and eventually constructed. I claim that
wonder is the missing element of Levinas' analysis, and it is also the
constituent of this ethical love dimension. In order to show that wonder
constitutes the ethical love dimension, I build on the essays by Levinas
and Irigaray as I investigate the subjective experience of sexuality,
deconstructing its objectifying power over the other and replacing it
with an expressive power from the other. Such an analysis is analogous
to Irigaray's of Levinas' essay, however it does not rely on the
concepts of masculinity and femininity. Instead, it relies only on the
concept of the sexual-other approached from the embodied self.

** Wonder as a Dimension of Love

Wonder, the “first passion” according to Descartes, constitutes the
motivation behind the movement of desire outwards, for wonder's “object”
is one that remains “impossible to delimit, im-pose, identify.” [56] If
desire is the mobility of the self into the world, into life, then
“wonder is the motivating force behind mobility in all its
dimensions.” [57] The other is thus pursued after by desire and through
wonder. One can look at the ego in a slightly different light now, for
the self is thrown into the world blindly, toward an unknown other. The
integral structure of the ego, then, is the mental faculty's reaction to
the chaos of this movement toward the infinite expanse (and abyss) of
the Other: it is the establishment of a relational knowledge-base, of
reason, of θεωρία. The ego searches for ground, and it finds its ground
in itself, in returning to itself. The integral structure of the ego is
the “return to” which Irigaray identifies: “Insofar as man or men are
concerned, it seems that auto-affection is possible only through a
search for the first home”---that is, the “first relation” and the
“dwelling place” of which Levinas writes---“...Love of self would
seemingly take the form of a /return/ to and through the other.” [58]
Irigaray here critiques the privileging of the movement of the ego:
θεωρία, the establishment of ground, the return to the dwelling. That
is, when a man achieves love of self, it is either a “nostalgia for the
mother-womb entity, [a] quest for God through the father, [or a] love of
one part of the self,” which relegates the female to become either the
“unique one” or the “infinite series of one plus one plus one... parts
of a broken whole.” [59] In this way, men don't truly love the other,
but they only love themselves by using the other for a specified end, as
an object of the ego's process to totalize the other. [60] When love
takes for itself a specified object---the unique one, the infinite
series, the progeny, the history---it ceases to be love and instead
assumes an egoist structure. In this scenario, above all, love has
failed to follow the task of ethics.

To maintain the infinite height of the other while also indulging in an
intimate romantic love relationship requires that wonder occupy a
fundamental position in the intersubjective space. We must not entirely
lose our childlike sense of wonder! Wonder is maintained in the way that
the self lovingly approaches the threshold of the sexual-other. This
approach is both initiated by the self, but also brought upon the self
by the other. As Irigaray observes, wonder is “an action that is both
active and passive.” [61] The task is to see whether and how intimacy
can uphold wonder.

Romantic-erotic love involves a feeling of /power/, evinced in the
moment of the sexual act. The intense intimacy felt during lovemaking
seems to include bringing the other into, if perhaps only briefly or
tangentially, one's totality, which constitutes a mastery of the self
over the other. It allows the ego to touch (but not grasp?) the
impossibility of the infinitude of the other. The ego thus seems to
accomplish its ultimate totalizing task in the sexual act: it is finally
able to seduce, subdue, overpower the other. But as soon as this
mastery---the sexual act---is accomplished, the moment passes, and the
impossible satisfaction returns to a desire and a longing for the sexual
act again. The totality of the ego seems to be broken, and the other is
returned to a state of infinite alterity.

This begs the questions: what is the totality of the ego if it can be so
quickly and easily broken? Is the totality broken when the other escapes
back, withdraws, into infinition? Isn't it a contradiction for the ego
to totalize infinitude, the infinite other? Does the ego really have so
much power as to direct the self /over/ the other? Is the egoist need
for totality actually being accomplished in the sexual act?

In orgasm, the ego comes infinitely close to totalizing the other, for
there is nothing more intimate to all of the senses than lovemaking
between two. However, the ego becomes suspended in orgasm, usurped by
the endless production of metaphysical desire. That is, in the sexual
act, desire accomplishes its productive task. It is free to nourish
itself endlessly: metaphysical desire uninhibited, pure enjoyment, which
can only occur when the ego is removed from the frontal location in the
human psyche, no longer filtering the world through its integral
structure of interiority-exteriority.

This ego-suspension is indicated most clearly by the satisfaction that
comes from orgasm. Satisfaction is only recognized after the fact: the
climactic of orgasm is perceived as fleeting. During the moment of
climax, there is no realization of satisfaction. One does not, cannot in
the moment, say “I am satisfied.” It is only after the fact, when the
ego returns to the foreground of the self, and recognizes what has just
taken place: it then lays the self next to the beloved and says, “I am
satisfied.” The producing power of desire, expressed without egoistic
control, manifests as love: “Love itself is thus taken to be the
satisfaction of a sublime hunger.” [62] Love procures a radical
dissociation of the self and the ego. The feeling of power is realized
to be an /apparent/ power over the other: apprehension of the other, not
comprehension. “The Other, whose exceptional presence is inscribed in
the ethical impossibility of killing him in which I stand, marks the end
of powers.” [63] The other may maintain their horizonal [64] distance in
this way, while the ego still receives the apparent power of
totalization that it craves. The needs of the ego are satisfied, and the
“infinition” of the other is upheld. [65]

The ego does not totalize the other completely, as it does with its
implements. Desire takes the self to the /threshold/ of the other. But
the self can only reach this threshold when the other is approached by
the self uninterpreted by the ego's integration of
interiority-exteriority: thus the ego is /necessarily/ lost in desire's
full production. The egoless self is opened to the experience of the
infinitude of the other unfiltered by the totalizing control of the
self's ego. The ego is then relegated to the background or
suspended--- /lifted, in ec-stasy, a new notion of exteriority/---as
desire maintains control of the self. The ego is not lost completely
because it is able to recognize that it is closer to the other than ever
before, and it returns. It comes infinitely close to totalizing the
other---this is the moment of orgasm as experienced by the ego. And
suddenly, the orgasmic moment is lost to the past. The ego is restored
to its control over the self in the aftermath of lovemaking and the
alterity of the other is restored in its infinitude. The ego has come
close to its goal, but in a moment the goal is lost. A renewed wonder
thus consumes the ego, a wonder situated temporally in that it is
acutely aware of the increasing time between the present moment and the
ecstasy of the love act as it escapes into the past.

The dissociation of the ego and the self at the moment of orgasm
provides desire with uninterpreted access to the other: an accession;
the /power/ felt in the moment comes from the other lifting the self to
the threshold of the other. Analogous to the ethical command /from/ the
other, this power is felt in the simultaneous act of desire's complete
production and the accession or the lift /from/ the Other. In the
romantic embrace, the withdrawal of the other into modesty is flooded by
desire and lifts the self with the other. Thus the other is maintained
in their alterity, their height, and reaches to the self, for to lift
the self is to reach to the primordial desire of the self, /to produce
the other at the self's in-stance, a new notion of interiority/. And it
is a power that is in effect gifted to the self from the other; thus the
empowered self---elevated by and in the pure enjoyment of the moment,
the new ec-stasy of the self, the new in-stance of the other---is
situated in a wonder-filled adoration toward the other. Wonder,
alongside desire, is actualized by the lift from the other and the
ego-suspension of the self. It is the concerted action of the two, the
couple, which instills the intimate with wonder and desire.

One must remember the proximity of the self and the ego with respect to
its needs. For lovemaking to suspend the ego, the arbiter of the self's
needs, and yet /still satisfy the self's needs/ is an act of a
profoundness that cannot be put into words---it is a profoundness that
can only be felt.

Finally one may conclude from this analysis that the persistent passion
in romantic-erotic love is desire: free to nourish itself endlessly,
desire is without constraint in the sexual act. It produces its own
satisfaction and is thus satisfied as if for the first time. The self is
finally granted unfiltered access to the infinitude of the other albeit
via desire, and not via the ego. Meanwhile, the ego indirectly achieves
its totalizing goal, but the satisfaction derived from totalizing the
other is lost in the fleeting moment of orgasm. Even after the apparent
totalization of the other, desire returns as the ego longs to experience
the other in the sexual act again. The self approaches and apprehends
the threshold of the other in this way.

** Wonder and Time

Some parts of the analysis must be uncovered further. How is it that
wonder can have so much impact over the self and the ego? The answer is
that wonder alters the relationship of the self to time, already a
tenuous relationship. The /post factum/ satisfaction of orgasm indicates
that the dissociation of desire and ego takes place in time. The ego
perceives time structurally, in the same integral fashion as it is wont
to return to itself. The integration of interiority-exteriority and the
establishment of a knowledge base embed the ego itself in an historical
time. Desire, on the other hand, produces endlessly, and has no return:
it is the originary of time, not yet assuming a structure, a history, a
past or a future. [66] In desire, time is not yet qualified, it is only
a first movement toward the other.

Irigaray asks rhetorically, “Is wonder the time that is always covered
over by the /present/? The bridge, the stasis, the moment of
/in-stance/?” [67] That is, wonder could mark the point of passage of
time /between/ the past and future, but also between “two closed worlds,
two definite universes,” or, two egos, the lover and the beloved.

The desiring self, motivated by wonder, levitates between the two
definite ego-selves within the love relationship: my ego is suspended,
but the other is found in their body here and now, in this new
in-stance, in a desire-time not yet qualified, and my I is instantiated
in the infinite threshold between the two, the ethical gap of the other:
wonder. A non-egoist time dimension is founded for the I, by the love of
the other, which lifts the self out of the control of the ego, out of
the ego's historical past and expectation of a future determined. This
is a new time dimension, qualified by desire /with/ the other: “The
beginning of a new story?” [68]

Wonder does not envelope the love relationship, nor does it constitute
or limit it. “It corresponds to time, to space-time before and after...
It constitutes an /opening/ prior to and following that which
surrounds...” [69] In other words, wonder is a time-opening prior to and
following the integral structure of the ego. It cannot be found,
observed, or recognized by the ego, for wonder is only present when
knowledge is not. (It is /wonder/ which causes poets to struggle as they
tell of love!) And wonder does not know a return to itself, as does the
ego; it is “without nostalgia for the first dwelling,” the habitation of
the self, the return of the ego. [70] Wonder only knows the motivation
of hunger in metaphysical desire. Indeed, without any return or
nostalgia, wonder can motivate an ever-new production of desire, the
same desire that originates an interior time dimension. With both
passions working in concert, wonder opens to the self a new desire-time
dimension and the other-in-love qualifies it. Thus, the other presents,
in-stance, as time itself. I open, ego suspended, and desire produces
the in-stance of the other as intimacy, the very name of the new time.

** Biological Sex, Sexual Orientation, and Gender Roles

In the discussion so far, I have attempted to use gender-neutral
language as much as possible. However, even such a term as “beloved” has
a bias, which seems to objectify the other in love. It is necessary at
this point to explain the very different definitions of sexuality and
gender and how they inform the present discussion.

Irigaray provides a strong framework for rethinking gender roles. By
abstracting masculinity and femininity to our phenomenological
experience of time and space respectively, we can escape traditional
stereotyping. I have shown how desire and wonder serve to situate the
self, the ego, and the other within space-time. Irigaray has shown how
the feminine relates to space, and the masculine to time. One can then
examine the masculine/feminine-male/female divide stochastically. The
inducer of this idea is the observation in biology that many species may
switch their sex given certain environmental or social situations. [71]
This biological capacity for switching sexes indicates, at a fundamental
level, a female potentiality within the male and, likewise, a male
potentiality within the female. The presence of the Y chromosome, [72]
then, is not a binary operation of deciding between male or female, but
an inductive mechanism that persuades the organism to tend toward one
pole or the other throughout its development from fetal to adult.

Along its developmental continuum, the cells of a fetus with a Y
chromosome would tend toward developing a male actuality, while the
cells of a fetus without a Y chromosome would tend toward developing a
female actuality. Because this development is probabilistic, the
organism does not statically situate itself within one end of the gender
bipole. Rather, the radical bipolarity present at the point of
conception is reduced to a tendency toward one pole, distributed over
the entirety of the parts (cells) of the organism. The process of this
tendency toward one pole is analogous to the change that a bimodal
statistical distribution undergoes when one of its means becomes
weighted more heavily than the other. This supports the assertion that
gender and sexuality are neither fixed, nor binary. Instead, they are
actualized potentialities of different /modes/ that an organism may
assume; collectively, this actualization of sexuality is observed as
/bimodal/. The gender classifications of masculine and feminine are only
two averages of the many possible modes of sexuality which are then
injected into and situated within the social.

The fact that this bimodality is distributed across the collective cells
of the organism indicates that sexuality is effectively unique. It is
highly unlikely that any two organisms will have the same distribution
of sexual modes across all of their cells, given that, in the case of
humans, each individual has some ten trillion cells. [73] Thus,
sexuality is /unique/ and /different/ among all individuals. If Irigaray
is correct in placing sexual difference at the base of sexual relations,
then it is not hard to imagine the myriad of different ways sexuality
could actualize and result in many different types of relationships.

This is a way of thinking to which Irigaray approaches. One could say
that Irigaray, in analyzing how man relates to time and woman to space,
is essentializing the genders. However, the above analysis indicates
that a binary understanding of gender roles is only a convenience which,
in the past, has been imported into the discussion when sexuality is
related to the social. In reality, sexuality is fluid and dynamic: it
can move from time to space, from space to time, and occupy any
differential between the two. To her credit, Irigaray anticipates my
analysis by saying that the two sexes must establish “a chiasmus or a
double loop in which each can go toward the other and come back to
itself. If these positive and negative poles are not found in both, the
same one always attracts, while the other remains in motion but lacks a
‘proper' place.” [74] Neither is static, but each sex moves toward and
away from its opposite and as such creates the necessary dynamism (as
well as the wonder that motivates desire) that an essential difference
of sexuality implies. This leads to the contemporary view that gender
roles exist on a spectrum, with which I agree.

However, the contemporary view on gender and sexuality is not complete.
There tend to be two predominant views on sexual orientation today:
either it is a choice of one's free will, or it is determined by some
biological situation. [75] Both of these arguments make it possible to
normalize sexual orientation into the archetypal stereotypes of the
past: if it is a matter of choice, then the individual must be
instructed to make the proper choice (heteronormativity) or suffer
punishment; if it is determined, then there must be some intervention in
which the subject's physiology is returned to the norm of
heterosexuality. Over time, if either of these actions are taken,
homosexuality would be eradicated and heterosexuality would become the
norm.

I disagree with both of these arguments. The present analysis opens the
way for a third view on sexual orientation: it is a combination of
choice and determination that orients one's sexuality. In this
perspective, there cannot be any imposed norm. The potential for
biological determinism is obscured in the complexity of the
probabilistic mode of sexual orientation. This probabilistic orientation
is only a suggestion for the individual because of the fact that it
retains the potentiality of the opposing sex: the male potentiality
within the female, the female potentiality within the male. It is then a
matter of choice (either consciously or subconsciously) for the
individual to accept or reject their inherent biological suggestion for
sexual orientation. No matter what they choose, there is no room for
justification of any imposed sexual norm. [76]

The most important point is to not confuse gender identities with sexual
orientations. Gender identities tend to take a binary form: either
masculine or feminine, gay or straight, transgender or cisgender. Sexual
orientation, on the other hand, refers to a stepwise process of
differentiating from one organism to the next within a population and
the “male” and “female” modes toward which these differentiations tend.
Neither “male” nor “female” necessarily exist in reality (i.e. nature,
evolution): they are only convenient abstractions of assumed tendencies,
they are merely representations. [77] The stepwise differentiation of
sexuality begets a spectrum of sexual modes; each organism as an
individual maintains their own sexuality, their own sexual mode. This in
no way allows for an imposed sexual norm---it is essentially
pluralistic. Thus is resolved the above-mentioned tension in Levinas:
biology itself is pluralistic, and allows for the (sexual) separation of
individuals which then draws them together in desire.

After all, even “homosexuality” as it is typically conceived---“man”
loving “man” and “woman” loving “woman”---is defined by gender roles of
“man” and “woman”; it does not actually have anything to do with
sexuality or sexual orientation. [78] Love is always love of /an other/,
no matter with which gender said other identifies. The opposite of
heterosexuality is not “homosexuality,” but autosexuality: love of the
same, love of the self, /love of the self-same/. In order for a
coming-together in love to exist, there must first be a separation of
individuals: this separation is sexuality itself, and the
differentiation of sexualities among individuals expresses itself as a
gradation of unique orientations. According to this analysis, the
question “Should love between (wo)men be tolerated?” is not even valid
because it assumes a sexual norm that cannot exist: it confuses gender
identities for sexual norms. In reality, even love between men is love
between two sexually differentiated individuals; though they might
identify with the same gender, this is no reason to criticize them on
their sexual orientations and romantic decisions. That is, any argument
against love between women or love between men is a category mistake
because love does not exist between genders, it exists from sexual
differences, and every individual is sexually unique.

** Monogamy and the Wedding

Today, monogamy seems to be falling out of favor. Rising divorce rates
and the plethora of arguments for polygamy---from quasi-biological
arguments regarding mate selection to the simple fact that people travel
now more than ever---make monogamy into an old-fashioned, out-of-date
concept. On the contrary, I develop here a concept of sexuality that
allows for a valid argument for monogamy that is not at all dependent on
gender opposites (that is, marriage between man and woman) nor
traditional institutions of religion and sexuality. The argument depends
only on the concept of the sexual-other.

I show above how every sexuality is a unique sexuality, and every sexual
relationship is heterosexual by degree of differentiation. If one
individual occupies a unique position on the sexual-orientation
spectrum, then it reasons that there exists an other on the spectrum
that is a relative reversal of the self's position; that is, for every
probabilistic component that makes up the self's sexuality, there is a
differential /complement/: a “filling up” and a /comple/tion of the
least-probable aspects of the self's sexuality by the sexual-other. This
is not a "whole" to be completed by predetermined parts as Levinas
claims, [79] but rather a completion of expression, in which the
nebulous and indeterminate nature of sexuality is made actual to the
furthest extent and most profound intent. If sexuality can be plotted as
a curve or a statistical distribution on a Cartesian plane, then the
self is the area under the curve, and the sexual-other the (infinite)
area above the curve: the horizon of sexual difference. [80] But this
sexual-area above/below the curve does not fill up like an opaque liquid
pouring into a cup; rather, it is like particles of gas, vibrating
within the plane of sexuality, continually de-charging and re-charging
each other within a stochastic chaos. The overall mode of this sexuality
is influenced by unconscious psycho-physiological mechanisms combining
with conscious preferences and desires. At any given moment, the self
and the sexual-other are in a state of flux while also remaining
complementary opposites. Each is ready to reverse itself in order to
complement the other---to rotate or flip the Cartesian plane by 180
degrees, so-to-speak---when the flux of sexuality necessitates it. When
the self refuses to abide by this adaptation of reversal, the bimodality
of the other's sexuality is reduced to a monomodality, the bipolarity of
the romantic relationship is reduced to a monopolarity, and the other
becomes over-powered by the self, objectified by a perpetual sexual
dominance. As Irigaray says, "sexual difference is not reducible to the
quantitative even though it is traditionally measured by such standards:
by /more/ or /less./" The above analysis reveals the mechanism of this
irreducibility to the quantitative, and it is precisely the romantic
relationship that properly treats this irreducibility as fundamental.

However, Irigaray's claim makes the observation that sexuality is and
has been typically thought of as quantitative; this quantitation must be
examined. There is a certain amount of dominance in the sexual act, but
this dominance always remains a sexual fantasy: the other is never
relegated to the defined “area under the curve,” but is always
conditioned by the infinite quality of the “area above the curve.” Above
I show that the power felt in the moment of the sexual act is actually
an apparent power of the ego; now this apparent power reveals itself as
the definition of the self's sexuality, the “area under the curve,” by
the infinite other-power, the “area over the curve.” The self never
dominates the other, nor does the other dominate the self; rather, the
probabilistic line that separates the self and the sexual-other is
momentarily defined in the sexual dimension. In the climactic of sexual
prowess, the self's sexuality is instantaneously defined in the
quantitative by the very founding of the new sexual dimension, that is,
intimacy with the sexual-other. The appearance of intimacy /must/ be
understood as this instantaneous quantitation and definition for it to
have such a profound effect on the self: in intimacy, the sexual-other
/removes my freedom/, and /defines/ my sexuality, which was never before
felt as definable (except through rationalization into gender
stereotypes, which are unsatisfying to the self's sexual desires). Of
course, this definition and quantitation is removed as quickly as it was
applied, but the experience nonetheless impresses the self. To be the
"area under the curve" is to take responsibility for the sexual-other's
pleasure; not to subordinate my lover for my own pleasure, but to become
responsible for /their/ pleasure. In doing so, I am gratified in my
sexuality, my lover's pleasure defines my sexuality as accomplished;
it's an empowering from the other. “Dominance” is thus lack of sexual
freedom, or the sexual dimension concretely defined by the the reversal
of interiority-exteriority: “the new ec-stasy of the self, the new
in-stance of the other.” During the sexual act, sexuality is no longer
open to probabilistic determination or social stereotypes. For a moment
sexuality is concretely and actually defined, devoid of any freedom or
interpretation, and yet it is still entirely complementary with the
sexual-other, a /comple/tion of sexuality. Individualism and the
individuals have no place in this intimate dimension: it is a space of
the couple, of /two/, in which the freedom of subjectivity is stripped
from the respective individuals and re-founded in the intimate space by
the love they share.

A popular phrase in romance literature and cinema is “you complete me.”
Interestingly enough, not only does this phrase take on a feminine
grammar according to Irigaray's analysis by announcing the other before
the self (as opposed to “I am completed by you,” for example) but this
is actually a real possibility and not an abstract ideal. The mechanics
for this actuality are clearly presented herein. The other completing
the self can now be described as the expression of romance and sexuality
between two in love and intimacy.

But one hurdle remains: that of secrecy. The intimacy of sexuality is
above defined as a “closed society,” totally private between lovers,
essentially a relationship of the secrets of the lovers. These secrets
can never be made public, but when one is truly in love, one wishes to
tell the world: the public celebration of the wedding. How is one to
fulfill this wish?

If Levinas' mistake in marking the /telos/ of /eros/ as the progeny got
something correct it was the unconditional love it allowed for the
child. As per the Irigarayan critique, however, this unconditional love
can no longer be contained in the same hierarchical structure that
Levinas employed. Instead, as I indicate earlier, it must be derived out
of this dimension of wonder.

** Psyche and Desire: A Reading of Apuleius' Metamorphoses

Psyche (ψυχή) is the Greco-Roman goddess of the soul, or more precisely,
the life force, the breath of life. In ancient Greek philosophy, every
living thing has a psyche, including plants and animals; the reasoning
faculties of the human only indicates a more complex psyche---it is a
matter of psyche-intensity which separates the species from plants to
animals to humans. In Apuleius, the figure of Psyche is presented as
absolute beauty, a human that rivals the untouchable beauty of the
goddess Venus. And yet the reader finds her in a tragic situation: her
sisters have all found love and husbands, while she continues without
either. As Fortune would have it, Venus becomes jealous of the human
Psyche's beauty (for even gods are subject to the whims of passion) and
commissions Cupid, Venus' son, to revenge her. However, Cupid falls in
love with Psyche and secretly takes her at night, without her ever
seeing his face or knowing whom he is.

Cupid is the Latin equivalent of the Greek god Eros, also named Amor and
Love. The passion of /eros/ plays an important role in the philosophy of
Plato, as /eros/ is that which directs one toward what one loves, in an
accession toward the good perhaps. It carries one, oftentimes against
one's better judgment and reason, to that which one desires. For Plato,
it is /eros/ that directs one toward the pursuit of knowledge; and
likewise it is /eros/ that directs one toward the erotic passions of the
body. Cupid, the embodiment of /eros/, cannot help but fall in love with
the beauty of Psyche---a beauty that is both human, of the body and the
earth, but also divine as it rivals that of Venus.

In the secrecy of the love-relations between Cupid and Psyche, Cupid
whisks Psyche to his palace where “he promised that she should have all
her wishes.” [81] She is served food and wine by invisible
servants---she only hears their voices around her; music is played by an
invisible lyrist on an invisible lyre. In the night, Cupid visits her,
loves her, consoles her; completely unseen, yet felt to every intensity
which love permits. Psyche admits that she falls deeply in love with
him: “I'd rather die a hundred times than lose your darling caresses. I
love you, desperately love you, whoever you are. I cherish you like my
own soul. I would not exchange you for Love himself.” [82] Despite the
invisibility of her lover Cupid, Psyche still falls “desperately” in
love with him.

In the archetypal portrayal of desire and love, one must first /see/ the
object of desire before one knows that one desires it. After recognizing
and acknowledging the object of desire, the subject pursues the object,
desiring to acquire the object that is now known. But in Apuleius,
Psyche does not know her lover; he is never seen, never named, never
understood, and yet he is Love itself and indeed she loves him. That is,
the Love of Psyche is not known at its genesis. It remains
unacknowledged until brought to light by Psyche's confession of it to
her sisters. (And in her curiosity to know her Love, she shines the
light of her lamp on Love's face, startling him and sending him away.)
Despite the unacknowledgement, however, Love is passionate,
all-embracing, and caring. Love takes Psyche in his arms, consoles her
and embraces her, or as Jupiter says, “Let him [Cupid/Love] hold her in
his arms and never depart from the delight of that embrace.” [83]

The great, timeless love of Psyche and Cupid is not one that takes the
form of an acquisitive desire, or need, but rather it is the production
of metaphysical desire. In fact, their love cannot be characterized as
one of acquisition, because the object of love, Cupid, is not yet known;
one cannot acquire what one does not yet know. The love of Psyche and
Cupid only produces itself: a continuous production of (always new)
love, which only takes itself, that is Love, as its object. A love that
is always new because it cannot take past love as its object, for that
would be to reduce it to a history, a nostalgia, and once again relegate
the movement of love to an acquisitive desire: a need to return to that
which one once had, to a history of past-time, to nostalgia.

One must note the obviously anthropomorphic signification of Psyche and
Cupid. Again, Psyche is the life force, the body animated (the flesh),
and that which defines life itself in all of its intensities, but is
also described as a beauty which rivals that of divinity; while Cupid is
precisely love and /eros/. This indicates that love as desire aims at
both the earthly flesh and the divine beauty of the other. It is /eros/
that allows one to be drawn toward the other in love. Cupid whisks
Psyche away unknowingly, in an air of mystery; love itself takes the
flesh and life of the lover into the intimate realm. It takes hold of
the self before the love sentiment is even known: one is aware that one
is in love before one knows /why/ they are in love, before they can
explicitly name the love, just as Psyche was embraced by Cupid before
she knew him: “the Love of Psyche is not known at its genesis.” Cupid
himself is love; psyche/life takes love itself as its object in love. Or
rather, the direction of predication is reversed. Cupid takes Psyche as
his lover, whisking her away to his palace of intimacy: /love takes life
as its subject/. And in this way, love may take over the self, producing
both bodily love of the flesh and divine love of beauty.

And after their wedding, Psyche and Cupid produce a daughter, Voluptas,
the goddess of bliss and enjoyment.

** Conclusion

Love of a person is not entirely unlike love of an idea. The lover of an
idea desires every possibility which the idea in-spires within them. The
lover's worldview is fundamentally changed by a powerful idea. The
ambitious lover will pursue the idea she loves with an unparalleled
intensity; she will even forget to sleep or to eat as she is caught up
in her passion and enjoyment for the idea. But an idea can be /known/,
eventually. Even the most lofty of ideas can be reduced to a form of
representation in knowledge. It is only the other /person/ that escapes
this totality and produces endless love. A lover of ideas and knowledge
is the individual that ultimately remains separated, isolated, and
removed from a society: is this not the great tragedy? The role of love,
then, is to create new societies of individuals-together, “private
societies” of the lovers.

However, love of an other person is unlike love of an idea because one
can never quite pursue after a person as they do an idea. One “closes
in” on an idea when one learns about it, and the idea becomes clearer
through time. By loving a person, the self does not “close in” on the
other person, but continually opens up: the loved other does not become
clearer in intimacy, but they become fluorescent; their alterity takes
on a never-ending depth that draws the self further into love.

If love can be ascribed a definition, it is this: to love is to open
oneself to the possibility of love, /to learn about love from the
other/, to let love take the self as its subject. This is the only
definition that allows for a multiplicity of love relationships, and yet
still upholds an ethical height of the other. This definition does not
explicitly name what love is, thus it does not relegate love to some
reductionist knowledge, but it still allows for a concrete realization
of love while resisting the temptation to confine love to a purely
abstract or ideal phenomenon. This love has no dependence on gender
identities or societal norms; it only depends on the (sexual-)other, the
separation that sexual differentiation implies, and the self's ability
to feel the passions of wonder and desire. Furthermore, there is nothing
"special" or "fantastic" about this love; in fact, sexual-otherness is a
very ordinary thing. The "magic" of love is created in the dynamism of
sexuality, in which the self changes in concert with the sexual-other to
maintain the completion of sexual-expression in romance. It is this very
dynamic-completion, actualized in the sexual dimension of intimacy,
which raises an ordinary couple to extraordinary heights. In this way,
any couple may create their own timeless love, like that of Cupid and
Psyche; it just takes a bit of work.

It is important that love is not named too explicitly, not brought to
the light of knowledge, especially within the romantic relationship. For
to do so will result in the lovers becoming “blinded by the light,” and
the illuminance of knowledge will efface any wonder that may have been
present. Love cannot exist for very long with so much light; it's best
to dim the lights ever-so, perhaps light a candle instead.

Finally, one can see how love literally creates societies, first by
establishing private societies of lovers, second by announcing said
societies as public, and third by progenating love onto the familial
structure. In doing this, as I have described here, love continually
follows the altruistic ethical framework that Levinas originated. The
only task left is to scale these love-societies and reconcile them with
the State.

One particularly important objection can be made against my argument:
that of sexual bias. I am a heterosexual male, and while I have taken
every step I could to use gender-neutral language and incorporate the
feminist/homosexual/transgender works available to me, it could still be
argued that my analysis contains a male's/man's bias. I admit this is a
bias worth investigating, and I openly welcome critique and addendum
from opposing sexes and genders. I think it would be particularly
interesting for a sexual-other of myself (e.g., a woman) to take up an
analysis of the passions of wonder and desire in sex from their point of
view. I presume that the role of the "apparent power" felt in the sexual
act may not be as prominent or as important as in my analysis; a woman's
analysis may take an entirely different route.

** Works Cited

Apuleius. /The Golden Ass/. Trans. Jack Lindsay. Bloomington, IN:
Indiana UP, 1962.

Beneke, Timothy. “Homophobia.” /Oppression, Privilege, & Resistance:
Theoretical Perspectives on Racism, Sexism, and Heterosexism./ Eds. Lisa
Heldke and Peg O'Connor. New York: McGraw-Hill, 2004.

Bem, Daryl. “Exotic Becomes Erotic: A Developmental Theory of Sexual
Orientation,” /Psychological Review/ 103.2 (1996): 320-35.

Bergo, Bettina, “Emmanuel Levinas”, The Stanford Encyclopedia of
Philosophy (Spring 2014 Edition), Edward N. Zalta (ed.), URL =
<http://plato.stanford.edu/archives/spr2014/entries/levinas/>.

Bleier, R. /Science and gender: A critique of biology and its theories
on women./ New York: Pergamon Press, 1984.

Bloechl, Jeffrey D. “How Best to Keep a Secret?” /Man and World/ 29.1
(1996): 1-17.

Futuyma, D.J., & Risch, S.J. “Sexual orientation, sociobiology, and
evolution.” /Journal of Homosexuality/, 9. (1983/84): 157-68.

Grosz, Elizabeth A. /Sexual subversions: three French feminists/. Allen
& Unwin Academic, 1989.

Hutchens, B. C. /Levinas: A Guide for the Perplexed/. New York:
Continuum, 2004.

Ince, Kate. "Questions to Luce Irigaray." /Hypatia/ 11.2 (1996): 122-40.
URL =
<[[http://www.jstor.org/stable/3810267][/http://www.jstor.org/stable/3810267/]]>.

Irigaray, Luce. /This Sex Which Is Not One./ Ithaca, N.Y.: Cornell
University Press, 1985.

---------. /An Ethics of Sexual Difference/. Ithaca, NY: Cornell
University Press, 1993.

Levinas, Emmanuel. /Totality and Infinity; an Essay on Exteriority/.
Trans. Lingis Alphonso. Pittsburgh: Duquesne UP, 1969.

---------. /Time and the Other: And Additional Essays/. Trans. Richard
A. Cohen. Pittsburgh: Duquesne UP, 1987.

Lynch, Michael. /The Origins of Genome Architecture/. Sunderland, MA:
Sinauer Associates, 2007.

Schroeder, Brian. /Altared Ground: Levinas, History, and Violence/. New
York: Routledge, 1996.

Valdes, Francisco. “Notes on the Conflation of Sex, Gender, and Sexual
Orientation.” /Oppression, Privilege, & Resistance: Theoretical
Perspectives on Racism, Sexism, and Heterosexism./ Eds. Lisa Heldke and
Peg O'Connor. New York: McGraw-Hill, 2004. Print.

Warner, R., D. Robertson, and E. Leigh. “Sex Change and Sexual
Selection.” /Science/ 190.4215 (1975): 633-38.

Warner, Robert R., and Ross Robertson. “Sexual Patterns in the Labroid
Fishes of the Western Caribbean, I the Wrasses (Labridae).” /Smithsonian
Contributions to Zoology/ 254 (1978): 1-27.

Endnotes

** Footnotes

[1] Bergo, Bettina, “Emmanuel Levinas”, The Stanford Encyclopedia of
    Philosophy (Spring 2014 Edition), Edward N. Zalta (ed.), URL =
    <[[http://plato.stanford.edu/archives/spr2014/entries/levinas/][/http://plato.stanford.edu/archives/spr2014/entries/levinas//]]>.

[2] Emmanuel Levinas, /Totality and Infinity; an Essay on
    Exteriority/. Trans. Lingis Alphonso. (Pittsburgh: Duquesne UP,
    1969), 152.

[3] /Ibid./, 153.

[4] /Ibid./, 165.

[5] /Ibid./, 152.

[6] /Ibid./, 152.

[7] /Ibid./, 152.

[8] /Ibid./, 114.

[9] /Ibid./, 114.

[10] Both Levinas and Irigaray often play with words, such as ecstasy
     and ec-stasy, to convey multiple depths of meaning behind what they
     say. Interestingly, neither of them do so with the word
     “independence.” The difference between “in dependence” and
     “independence” is subtle but important. The preposition “in” means
     “within, or inside.” The French root of independence,
     /indépendance/, refers to the /opposite/ of dependence, which is
     not what Levinas refers to. So the correct term to use is “in
     dependence,” because Levinas refers to a mastery within the
     organism's dependence on its needs.

[11] See in particular Levinas, /Totality and Infinity/, 37-38, as
     well as 59.

[12] Levinas, /Totality and Infinity/, 216.

[13] In the standard translation by Alphonso Lingis, this phrase is
     rendered as quoted in Levinas, /Totality and Infinity,/ 39. In his
     /Altared Ground/, Brian Schroeder translates this as “The
     absolutely other is the other person” (20). It is important to note
     that the Other /is/ the other person, for Levinas, and not an
     abstract generality of “other” or “otherness.” Levinas uses the
     French-derived word “alterity” to refer specifically to
     “otherness,” or the quality of being other.

[14] See Levinas, /Totality and Infinity/, 194-204 for the most
     relevant discussion of the Face.

[15] Levinas here implicitly relies on Maurice Merleau-Ponty,
     /Phenomenology of Perception/ (New York: Humanities Press, 1962).

[16] Paraphrased from Levinas, "Ethics and the Face," /Totality and
     Infinity/, 198-99.

[17] Levinas, /Totality and Infinity/, 196.

[18] A very different situation than in traditional ethics. Levinas
     says that, while an ethical situation begins as exteriority (which
     itself may be either objective or subjective exteriority) it
     doesn't become real until felt interiorly. And so, Levinasian
     ethics is an ethics not of independence or dependence, but of
     /inter/dependence between/with two.

[19] Levinas, /Totality and Infinity/, 216.

[20] /Ibid./, 33.

[21] /Ibid./, 34.

[22] The proximity of need and desire, and the occasional confusion
     between the two, show how closely related need is to Levinas'
     metaphysical desire. Likewise, since the ego is the arbiter of the
     satisfaction of needs, it shows how close the ego is to the self,
     even though I have been discussing them in language, which could
     make them seem as if they are distinctly separate entities.

[23] Levinas, /Totality and Infinity/, 29.

[24] This critique is plainly described by B.C. Hutchens, /Levinas: A
     Guide for the Perplexed/ (New York: Continuum, 2004), 155-65.

[25] Levinas, /Totality and Infinity/, 121.

[26] /Ibid./, 258.

[27] /Ibid./

[28] /Ibid./, 264.

[29] /Ibid./, 264-65.

[30] /Ibid./, 266.

[31] /Ibid./, 256.

[32] /Ibid./, 155.

[33] /Ibid./, 264.

[34] Luce Irigaray, /An Ethics of Sexual Difference/ (Ithaca, NY:
     Cornell University Press, 1993), 134-36.

[35] Irigaray, /Ethics/, 136.

[36] /Ibid./, 137.

[37] /Ibid./, 140.

[38] /Ibid./, 146-47.

[39] See Levinas, /Totality and Infinity/, 266 ("Already the relation
     with the child---the coveting of the child, both other and
     myself---takes form in voluptuosity, to be accomplished in the
     child himself") and 276 ("My child is a stranger, but a stranger
     who is not only mine, for he /is/ me. He is a stranger to myself").

[40] Irigaray, /Ethics/, 189.

[41] Elizabeth A. Grosz, /Sexual subversions: three French feminists/,
     (Allen & Unwin Academic, 1989) 142.

[42] Kate Ince, "Questions to Luce Irigaray," /Hypatia/ 11.2 (1996):
     125. URL = <[[http://www.jstor.org/stable/3810267][/http://www.jstor.org/stable/3810267/]]>.

[43] Ince, "Questions to Luce Irigaray", 123. In explaining this, Ince
     cites Jacques Derrida, "Interview: Choreographies: Jacques Derrida
     and Christie V. McDonald," /Diacritics/ 12.2 (1982): 66-76.

[44] Irigaray, /Ethics/, 178.

[45] As Lacan said "there is no Other of the Other," there is only an
     Other of the Same, Irigaray says that woman is the Other of the
     Other, and that to characterize woman as the Other of the Same is
     to subordinate woman to man's whims.

[46] Ince, "Questions to Luce Irigaray", 123.

[47] Levinas, /Totality and Infinity/, 151.

[48] Ince, "Questions to Luce Irigaray", 123: "If the face-to-face
     relation is untotalizable, why call it a dialectic at all? ... When
     [Levinas] uses the word 'dialectic,' it is to refer to a dialectic
     of being which leads not to unity but to plurality. It is with this
     aim of plurality that Levinas sets himself firmly against the
     Parmenidean conception of the unity of being which has dominated
     Western philosophy, instigating and maintaining the bias of
     ontology over ethics which he seeks to reverse." Ince cites
     Emmanual Levinas, /Le temps et l'autre/, (Paris: Quadrige/Presses
     Universitaires de France, 1979), 18-20, in support of this stance.

[49] Levinas, /Totality and Infinity/, 261.

[50] /Ibid./, 49.

[51] Emmanuel Levinas and Richard A. Cohen, /Time and the Other: And
     Other Essays/ (Pittsburgh: Duquesne University Press, 1987), 257.

[52] Ince, "Questions to Luce Irigaray," 128.

[53] Irigaray, /Ethics/, 195.

[54] /Ibid./, 26.

[55] Ince, "Questions to Luce Irigaray," 129.

[56] Irigaray, /Ethics/, 81.

[57] /Ibid./, 73.

[58] /Ibid./, 60.

[59] /Ibid./, 61.

[60] A psychoanalytic description of this is given in Luce Irigaray,
     /This Sex Which Is Not One/, (Ithaca, N.Y.: Cornell University
     Press, 1985), 25.

[61] Irigaray, /Ethics/, 73.

[62] Levinas, /Totality and Infinity/, 34.

[63] /Ibid./, 87.

[64] Irigaray uses this term to relate to the “horizon” of the other.
     Just as the horizon is always in the distance, so too is the other.
     See /Ethics/, 70.

[65] For an explanation of the term "infinition," see Levinas,
     /Totality and Infinity/, 281-82.

[66] Irigaray, /Ethics/, 76.

[67] /Ibid./, 75.

[68] /Ibid./, 75.

[69] /Ibid./, 81-2.

[70] /Ibid./, 82.

[71] See Warner, R., D. Robertson, and E. Leigh, “Sex Change and
     Sexual Selection,” /Science/ 190.4215 (1975): 633-38 and Warner,
     Robert R., and Ross Robertson, “Sexual Patterns in the Labroid
     Fishes of the Western Caribbean, I the Wrasses
     (Labridae),” /Smithsonian Contributions to Zoology/ 254 (1978):
     1-27 for the relevant observations in marine biology.

[72] The biological specifics aren't important to this discussion. In
     fact, recent research has shown that the Y chromosome is /not/ the
     only factor to sexual determination, which supports my argument to
     the indeterminate quality of sexual actualization. For purposes of
     this discussion, interpret “Y chromosome” as “that which influences
     sexed biological condition.”

[73] This estimate is given in Lynch, Michael, /The Origins of Genome
     Architecture/ (Sunderland, MA: Sinauer Associates, 2007).

[74] Irigaray, /Ethics/, 9.

[75] Contrary to popular belief, the claim that sexuality is
     determined genetically has been refuted on theoretical,
     metatheoretical, and empirical grounds according to D.J. Futuyma
     and S.J. Risch, “Sexual orientation, sociobiology, and evolution.”
     /Journal of Homosexuality/, 9. (1983/84): 157-68, and has even been
     shown to be circular by R Bleier,, /Science and gender: A critique
     of biology and its theories on women/ (New York: Pergamon Press,
     1984).

[76] A similar analysis is described by Timothy Beneke, “Homophobia,”
     /Oppression, Privilege, & Resistance: Theoretical Perspectives on
     Racism, Sexism, and Heterosexism,/ Eds. Lisa Heldke and Peg
     O'Connor, (New York: McGraw-Hill, 2004). In citing the work of
     Richard Isay, Beneke says, “I believe that we come into the world
     with biologically based impulsions to be sexually attracted to
     either the same or the opposite sex, or in varying degrees, both,
     and that social context and the social generally can powerfully,
     sometimes transiently, influence object choice” (225). For the
     psychoanalytic theory and evidence of this idea, see Daryl Bem,
     “Exotic Becomes Erotic: A Developmental Theory of Sexual
     Orientation,” /Psychological Review/ 103 no. 2 (1996): 320-35. I
     tend to agree with these authors, except for the fact that they
     still assume a binary sexuality by saying, "the same or opposite
     sex," as if those are the only two possible manifestations of
     sexuality.

[77] In fact, a problematic assumption is uncovered when sexual
     orientation is derived exclusively from evolutionary sex. “For
     example, the belief that sexual orientation is encoded in the genes
     embodies the unacknowledged assumption that knowledge of the
     distinction between male and female must also be hardwired into the
     human species, that sex is a natural category of human perception”
     (Bem, "Exotic Becomes Erotic," 1996). A few sentences later, this
     assumption is shown to be empirically unsupported.

[78] Here I am only analyzing sexual orientation, specifically by
     distinguishing it from gender classifications. I make no further
     claims about gender, nor does my forthcoming analysis depend on any
     gender-related concepts. For a more complete exposé of the
     differences of (and socioeconomic factors related to) sex, sexual
     orientation, and gender, refer to Francisco Valdes, “Notes on the
     Conflation of Sex, Gender, and Sexual Orientation,” /Oppression,
     Privilege, & Resistance: Theoretical Perspectives on Racism,
     Sexism, and Heterosexism,/ Eds. Lisa Heldke and Peg O'Connor (New
     York: McGraw-Hill, 2004.).

[79] Levinas, /Totality and Infinity/, 49.

[80] Is the sexual-other perhaps the /negative/ of the integral of the
     self's sexuality? Or, why has mathematics not studied the area
     above the curve as it has studied the integral, the area below the
     curve?

[81] Apuleius, /The Golden Ass/, Trans. Jack Lindsay (Bloomington, IN:
     Indiana UP, 1962) 113.

[82] /Ibid./ Psyche's last sentence is, of course, a wonderful irony.

[83] /Ibid./, 141.
